In [1]:
from src.res.model.model_module.application import ArchivedPredictorModel
model = ArchivedPredictorModel.from_model_str('gru@gru_avg@0')

In [ ]:
block = model.hidden_block(20170101 , 20170105 , 20170103 , silent = False)

In [3]:
from src.res.model.model_module.application import ArchivedPredictorModel
model = ArchivedPredictorModel.from_model_str('gru@gru_day@0')

In [ ]:
block = model.hidden_block(20170101 , 20170105 , 20170103 , silent = False)

In [5]:
block.date

array([20170103, 20170104, 20170105, 20170106, 20170109, 20170110,
       20170111, 20170112, 20170113, 20170116, 20170117, 20170118,
       20170119, 20170120, 20170123, 20170124, 20170125, 20170126,
       20170203, 20170206, 20170207, 20170208, 20170209, 20170210,
       20170213, 20170214, 20170215, 20170216, 20170217, 20170220,
       20170221, 20170222, 20170223, 20170224, 20170227, 20170228,
       20170301, 20170302, 20170303, 20170306, 20170307, 20170308,
       20170309, 20170310, 20170313, 20170314, 20170315, 20170316,
       20170317, 20170320, 20170321, 20170322, 20170323, 20170324,
       20170327, 20170328, 20170329, 20170330, 20170331, 20170405,
       20170406, 20170407, 20170410, 20170411, 20170412, 20170413,
       20170414, 20170417, 20170418, 20170419, 20170420, 20170421,
       20170424, 20170425, 20170426, 20170427, 20170428, 20170502,
       20170503, 20170504, 20170505, 20170508, 20170509, 20170510,
       20170511, 20170512, 20170515, 20170516, 20170517, 20170518,
       20170519, 20170522, 20170523, 20170524, 20170525, 20170526,
       20170531, 20170601, 20170602, 20170605, 20170606, 20170607,
       20170608, 20170609, 20170612, 20170613, 20170614, 20170615,
       20170616, 20170619, 20170620, 20170621, 20170622, 20170623,
       20170626, 20170627, 20170628, 20170629, 20170630, 20170703,
       20170704, 20170705, 20170706, 20170707, 20170710, 20170711,
       20170712, 20170713, 20170714, 20170717, 20170718, 20170719,
       20170720, 20170721, 20170724, 20170725, 20170726, 20170727,
       20170728, 20170731, 20170801, 20170802, 20170803, 20170804,
       20170807, 20170808, 20170809, 20170810, 20170811, 20170814,
       20170815, 20170816, 20170817, 20170818, 20170821, 20170822,
       20170823, 20170824, 20170825, 20170828, 20170829, 20170830,
       20170831, 20170901, 20170904, 20170905, 20170906, 20170907,
       20170908, 20170911, 20170912, 20170913, 20170914, 20170915,
       20170918, 20170919, 20170920, 20170921, 20170922, 20170925,
       20170926, 20170927, 20170928, 20170929, 20171009, 20171010,
       20171011, 20171012, 20171013, 20171016, 20171017, 20171018,
       20171019, 20171020, 20171023, 20171024, 20171025, 20171026,
       20171027, 20171030, 20171031, 20171101, 20171102, 20171103,
       20171106, 20171107, 20171108, 20171109, 20171110, 20171113,
       20171114, 20171115, 20171116, 20171117, 20171120, 20171121,
       20171122, 20171123, 20171124, 20171127, 20171128, 20171129,
       20171130, 20171201, 20171204, 20171205, 20171206, 20171207,
       20171208, 20171211, 20171212, 20171213, 20171214, 20171215,
       20171218, 20171219, 20171220, 20171221, 20171222, 20171225,
       20171226, 20171227, 20171228, 20171229])

In [2]:
batch_data = model.batch_data(20170104 , 0 , 'best')
batch_data.output.hidden

tensor([[-0.3915, -0.3443,  0.4069,  ...,  0.3598,  0.3319, -0.3887],
        [-0.0589, -0.1906,  0.0775,  ...,  0.0372,  0.0869, -0.1593],
        [ 0.0388, -0.1517, -0.0289,  ..., -0.0538, -0.0040, -0.0741],
        ...,
        [-0.2409, -0.2720,  0.2601,  ...,  0.1993,  0.2109, -0.2853],
        [ 0.0330, -0.1552, -0.0160,  ..., -0.0414,  0.0092, -0.0794],
        [ 0.0763, -0.1266, -0.1034,  ..., -0.1166, -0.0764, -0.0572]],
       device='mps:0')

In [ ]:
batch_data.hidden_df_pl(colname_prefix = model.model.model_full_name)

shape: (2_475, 34)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ secid  ┆ date     ┆ gru_avg@0@ ┆ gru_avg@0@ ┆ … ┆ gru_avg@0@ ┆ gru_avg@0 ┆ gru_avg@0 ┆ gru_avg@0 │
│ ---    ┆ ---      ┆ 20170103@b ┆ 20170103@b ┆   ┆ 20170103@b ┆ @20170103 ┆ @20170103 ┆ @20170103 │
│ i64    ┆ i64      ┆ est.hidden ┆ est.hidden ┆   ┆ est.hidden ┆ @best.hid ┆ @best.hid ┆ @best.hid │
│        ┆          ┆ …          ┆ …          ┆   ┆ …          ┆ den…      ┆ den…      ┆ den…      │
│        ┆          ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│        ┆          ┆ f32        ┆ f32        ┆   ┆ f32        ┆ f32       ┆ f32       ┆ f32       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1      ┆ 20170104 ┆ -0.391518  ┆ -0.344337  ┆ … ┆ -0.531863  ┆ 0.359802  ┆ 0.331948  ┆ -0.388693 │
│ 2      ┆ 20170104 ┆ -0.058927  ┆ -0.190594  ┆ … ┆ -0.210109  ┆ 0.037165  ┆ 0.086898  ┆ -0.159343 │
│ 4      ┆ 20170104 ┆ 0.038837   ┆ -0.151741  ┆ … ┆ -0.096914  ┆ -0.053778 ┆ -0.003955 ┆ -0.07411  │
│ 5      ┆ 20170104 ┆ -0.327795  ┆ -0.319639  ┆ … ┆ -0.460516  ┆ 0.310246  ┆ 0.262872  ┆ -0.339074 │
│ 6      ┆ 20170104 ┆ -0.358319  ┆ -0.339356  ┆ … ┆ -0.486123  ┆ 0.333871  ┆ 0.301682  ┆ -0.368806 │
│ …      ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 603993 ┆ 20170104 ┆ -0.61449   ┆ -0.473215  ┆ … ┆ -0.767785  ┆ 0.620125  ┆ 0.511186  ┆ -0.545246 │
│ 603996 ┆ 20170104 ┆ 0.102553   ┆ -0.117309  ┆ … ┆ -0.047386  ┆ -0.143748 ┆ -0.106214 ┆ -0.039728 │
│ 603997 ┆ 20170104 ┆ -0.240882  ┆ -0.27201   ┆ … ┆ -0.37392   ┆ 0.199293  ┆ 0.210866  ┆ -0.285268 │
│ 603998 ┆ 20170104 ┆ 0.033038   ┆ -0.155186  ┆ … ┆ -0.104923  ┆ -0.041392 ┆ 0.009166  ┆ -0.079417 │
│ 603999 ┆ 20170104 ┆ 0.076266   ┆ -0.1266    ┆ … ┆ -0.07401   ┆ -0.116563 ┆ -0.07642  ┆ -0.057189 │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
model.model.model_full_name

'gru_avg@0@20170103@best'

In [5]:
self = batch_data
narrow_df = False
colnames = None
kwargs = {}
df = self.output.hidden_df(self.input.secid , self.input.date , narrow_df , colnames , **kwargs)
df

,secid,date,hidden.0,hidden.1,hidden.2,hidden.3,hidden.4,hidden.5,hidden.6,hidden.7,...,hidden.22,hidden.23,hidden.24,hidden.25,hidden.26,hidden.27,hidden.28,hidden.29,hidden.30,hidden.31
0,1,20170104,-0.391518,-0.344337,0.406918,-0.225742,0.285869,0.374660,-0.469164,-0.596640,...,0.407911,0.476768,-0.290183,0.495487,-0.285819,0.249938,-0.531863,0.359802,0.331948,-0.388693
1,2,20170104,-0.058927,-0.190594,0.077464,-0.033737,0.137214,0.151932,-0.218867,-0.284296,...,0.137510,0.103417,-0.052434,0.170727,-0.186179,0.201606,-0.210109,0.037165,0.086898,-0.159343
2,4,20170104,0.038837,-0.151741,-0.028914,0.028889,0.095117,0.085681,-0.130099,-0.170050,...,0.054164,-0.015479,0.000316,0.065769,-0.165891,0.185035,-0.096914,-0.053778,-0.003955,-0.074110
3,5,20170104,-0.327795,-0.319639,0.337783,-0.178439,0.219783,0.336259,-0.409689,-0.474307,...,0.318023,0.413722,-0.276473,0.426716,-0.230133,0.228716,-0.460516,0.310246,0.262872,-0.339074
4,6,20170104,-0.358319,-0.339356,0.365467,-0.195653,0.246621,0.353017,-0.420752,-0.515434,...,0.345857,0.450354,-0.291279,0.451860,-0.238433,0.243157,-0.486123,0.333871,0.301682,-0.368806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,603993,20170104,-0.614490,-0.473215,0.620225,-0.356039,0.385718,0.575591,-0.618538,-0.768813,...,0.572884,0.726447,-0.495292,0.731482,-0.322466,0.280322,-0.767785,0.620125,0.511186,-0.545246
2471,603996,20170104,0.102553,-0.117309,-0.135474,0.111714,0.065442,0.050526,-0.051115,-0.102235,...,-0.025234,-0.110224,0.071251,0.003310,-0.160222,0.146373,-0.047386,-0.143748,-0.106214,-0.039728
2472,603997,20170104,-0.240882,-0.272010,0.260052,-0.128180,0.204387,0.250961,-0.356183,-0.449737,...,0.280180,0.311543,-0.185225,0.333853,-0.233178,0.231837,-0.373920,0.199293,0.210866,-0.285268
2473,603998,20170104,0.033038,-0.155186,-0.015973,0.012431,0.098326,0.088476,-0.130920,-0.174361,...,0.058362,-0.004304,-0.013330,0.072820,-0.168894,0.194204,-0.104923,-0.041392,0.009166,-0.079417
2474,603999,20170104,0.076266,-0.126600,-0.103373,0.091100,0.076769,0.067720,-0.077388,-0.124910,...,-0.002689,-0.076173,0.061462,0.029018,-0.162661,0.154621,-0.074010,-0.116563,-0.076420,-0.057189

In [3]:
batch_data.hidden_df

AttributeError: 'BatchData' object has no attribute 'hidden_df'

In [2]:
for batch_data in model.iter_batch_data(0 , 20170103 , 20170101 , 20170105):
    print(batch_data.batch_date)

BaseModelConfig Caution: Should be at server or short_test, but short_test is False now!
  --> Timer(Load DataBlock [y,day] at 20070104~20241211) finished! Cost 1.2948 Sec
  --> Timer(Align DataBlock [y,day]) finished! Cost 0.0019 Sec
20170103
20170104
20170105

In [3]:
model.dataloader.batch_dates

[20170103,
 20170104,
 20170105,
 20170106,
 20170109,
 20170110,
 20170111,
 20170112,
 20170113,
 20170116,
 20170117,
 20170118,
 20170119,
 20170120,
 20170123,
 20170124,
 20170125,
 20170126,
 20170203,
 20170206,
 20170207,
 20170208,
 20170209,
 20170210,
 20170213,
 20170214,
 20170215,
 20170216,
 20170217,
 20170220,
 20170221,
 20170222,
 20170223,
 20170224,
 20170227,
 20170228,
 20170301,
 20170302,
 20170303,
 20170306,
 20170307,
 20170308,
 20170309,
 20170310,
 20170313,
 20170314,
 20170315,
 20170316,
 20170317,
 20170320,
 20170321,
 20170322,
 20170323,
 20170324,
 20170327,
 20170328,
 20170329,
 20170330,
 20170331,
 20170405,
 20170406,
 20170407,
 20170410,
 20170411,
 20170412,
 20170413,
 20170414,
 20170417,
 20170418,
 20170419,
 20170420,
 20170421,
 20170424,
 20170425,
 20170426,
 20170427,
 20170428,
 20170502,
 20170503,
 20170504,
 20170505,
 20170508,
 20170509,
 20170510,
 20170511,
 20170512,
 20170515,
 20170516,
 20170517,
 20170518,
 20170519,
 20170522,
 20170523,
 20170524,
 20170525,
 20170526,
 20170531,
 20170601,
 20170602,
 20170605,
 20170606,
 20170607,
 20170608,
 20170609,
 20170612,
 20170613,
 20170614,
 20170615,
 20170616,
 20170619,
 20170620,
 20170621,
 20170622,
 20170623,
 20170626,
 20170627,
 20170628,
 20170629,
 20170630,
 20170703,
 20170704,
 20170705,
 20170706,
 20170707,
 20170710,
 20170711,
 20170712,
 20170713,
 20170714,
 20170717,
 20170718,
 20170719,
 20170720,
 20170721,
 20170724,
 20170725,
 20170726,
 20170727,
 20170728,
 20170731,
 20170801,
 20170802,
 20170803,
 20170804,
 20170807,
 20170808,
 20170809,
 20170810,
 20170811,
 20170814,
 20170815,
 20170816,
 20170817,
 20170818,
 20170821,
 20170822,
 20170823,
 20170824,
 20170825,
 20170828,
 20170829,
 20170830,
 20170831,
 20170901,
 20170904,
 20170905,
 20170906,
 20170907,
 20170908,
 20170911,
 20170912,
 20170913,
 20170914,
 20170915,
 20170918,
 20170919,
 20170920,
 20170921,
 20170922,
 20170925,
 20170926,
 20170927,
 20170928,
 20170929,
 20171009,
 20171010,
 20171011,
 20171012,
 20171013,
 20171016,
 20171017,
 20171018,
 20171019,
 20171020,
 20171023,
 20171024,
 20171025,
 20171026,
 20171027,
 20171030,
 20171031,
 20171101,
 20171102,
 20171103,
 20171106,
 20171107,
 20171108,
 20171109,
 20171110,
 20171113,
 20171114,
 20171115,
 20171116,
 20171117,
 20171120,
 20171121,
 20171122,
 20171123,
 20171124,
 20171127,
 20171128,
 20171129,
 20171130,
 20171201,
 20171204,
 20171205,
 20171206,
 20171207,
 20171208,
 20171211,
 20171212,
 20171213,
 20171214,
 20171215,
 20171218,
 20171219,
 20171220,
 20171221,
 20171222,
 20171225,
 20171226,
 20171227,
 20171228,
 20171229]

In [3]:
from src.res.factor.calculator import StockFactorHierarchy
calc = StockFactorHierarchy.get_factor('event_factor_momentum')()
calc.eval_factor_series(20241231)

Caution : Purging pooling weight of event_factor_momentum!

ValueError: factor weight is missing for ['atr_1m' 'ff_r2_1m']

In [1]:
from src.res.model.util import ModelPath
model_path = ModelPath('models/nn/gru@gru_global2top')

In [2]:
model_path2 = model_path.with_new_index(2)

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************