In [1]:
from src.data.util.classes.module_data import ModuleData

module_date = ModuleData(data_type_list = ['day'])
module_date.load()

  --> Timer(Load DataBlock [y,day] at 20070104~20241211) finished! Cost 1.5 Sec
  --> Timer(Align DataBlock [y,day]) finished! Cost <1 Sec

In [ ]:
from src.proj import MACHINE

MACHINE.config.get('constant/data' , 'calendar')

FileNotFoundError: Config file setting/model does not exist

In [16]:
import warnings
import pandas as pd

paths = [
    'models/nn/gru@gru_day/snapshot/pred_recorder/preds/1.20240604.20240605.20241129.feather',
    'models/nn/gru@gru_day/snapshot/pred_recorder/preds/0.20240604.20240605.20241129.feather',
]
preds = pd.concat([pd.read_feather(p) for p in paths])


grouped = preds.groupby(by=['model_num' , 'model_date' , 'submodel' , 'date'], as_index=True)
def df_ic(subdf : pd.DataFrame , **kwargs):
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', message='An input array is constant; the correlation coefficient is not defined' , category=RuntimeWarning)
        warnings.filterwarnings('ignore', message='invalid value encountered in divide' , category=RuntimeWarning)
        return subdf[['pred']].corrwith(subdf['label'], method='spearman')
new_df = grouped.apply(df_ic , include_groups = False).rename(columns = {'pred' : 'value'}).reset_index(drop=False)

In [17]:
new_df

     model_num  model_date submodel      date     value
0            0    20240604     best  20240605 -0.014204
1            0    20240604     best  20240606 -0.004220
2            0    20240604     best  20240607 -0.036864
3            0    20240604     best  20240611  0.017950
4            0    20240604     best  20240612  0.018406
..         ...         ...      ...       ...       ...
715          1    20240604  swalast  20241125  0.069943
716          1    20240604  swalast  20241126  0.077035
717          1    20240604  swalast  20241127  0.072671
718          1    20240604  swalast  20241128  0.094418
719          1    20240604  swalast  20241129  0.147890

[720 rows x 5 columns]

In [9]:
preds

,model_num,model_date,submodel,batch_idx,secid,date,pred,label
0,1,20240604,best,0,1,20240605,1.354189,0.458154
1,1,20240604,best,0,2,20240605,-12.804926,-0.105040
2,1,20240604,best,0,4,20240605,-11.466960,1.901116
3,1,20240604,best,0,6,20240605,-3.513626,1.672083
4,1,20240604,best,0,7,20240605,2.455589,-0.004313
...,...,...,...,...,...,...,...,...
5214,0,20240604,swabest,119,873679,20241129,-5.696887,-2.454074
5215,0,20240604,swabest,119,873693,20241129,11.973999,-2.572160
5216,0,20240604,swabest,119,873703,20241129,11.484550,-0.002630
5217,0,20240604,swabest,119,873726,20241129,-5.711055,-1.371403
5218,0,20240604,swabest,119,873833,20241129,-60.690815,-2.816562

In [7]:
module_date.y.values[:,-12:].isfinite().any(dim=(0))

tensor([[[ True, False,  True, False,  True, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]],

        [[False, False, False, False, False, False]]])

In [1]:
import pandas as pd
path = 'models/factor/df_scores_v0/snapshot/detailed_alpha/factor_perf_test/factor_stats/ic/bm=None.n=10.lag=2.ic=spearman.ret=close.feather'
pd.read_feather(path)

factor_name      best
date
20180102     0.155504
20180109     0.228894
20180116     0.255422
20180123     0.332879
20180130     0.292589
...               ...
20250331     0.169998
20250403     0.031051
20250408     0.278118
20250411     0.107788
20250415     0.211760

[362 rows x 1 columns]

In [6]:
from src.res.model.model_module.application.trainer import ModelTrainer
from src.res.factor.util.stats.aggregate import eval_period_ic_multi
from src.proj import PATH , DB

from pathlib import Path


def model_ic_summary():
    paths : dict[str , Path] = {}
    
    model_paths = ModelTrainer.all_resumable_models()
    for model_path in model_paths:
        if (path := model_path.snapshot('basic_test' , f'test_by_date.feather')).exists():
            paths[model_path.model_name] = path
    ic_tables = {}
    for name , path in paths.items():
        df = DB.load_df(path)
        ic_tables[name] = df.astype({'date' : 'int'}).query('submodel == "best"').groupby('date')['value'].mean().\
            reset_index(drop = False).dropna().rename(columns = {'value' : 'ic'})
    df = eval_period_ic_multi(ic_tables)
    return df

def display_ic_summary(by_max_columns : int = 12):
    df = model_ic_summary()
    for i in range(0, len(df.columns), by_max_columns):
        print(df.iloc[:,i:i+by_max_columns].dropna(how = 'all'))

display_ic_summary(2)

           df_scores_v0 df_scores_v2
period
Start          20180102     20180102
End            20250402     20250402
Avg              12.47%       13.32%
Sum              216.88       231.70
Std               7.97%        8.74%
T                 65.27        63.57
IR                 7.67         7.47
Y2018            17.92%       18.97%
Y2019            14.35%       15.83%
Y2020            12.99%       13.79%
Y2021            10.32%       10.94%
Y2022            10.63%       11.87%
Y2023            11.64%       12.01%
Y2024             9.03%        9.54%
Y2025            13.32%       13.49%
Last Day         11.21%       14.53%
Last Week         9.30%       11.40%
Last Month       18.29%       20.97%
Last Qtr         13.32%       13.49%
Last Year        10.64%       10.28%
           df_scores_v3 ht_master_combined
period
Start          20180102           20180102
End            20250402           20250402
Avg              13.66%             13.37%
Sum              237.63             232.63
Std               8.21%              9.36%
T                 69.40              59.55
IR                 8.15               6.99
Y2018            19.12%             17.62%
Y2019            15.80%             14.15%
Y2020            13.75%             13.91%
Y2021            11.21%             11.10%
Y2022            12.02%             12.65%
Y2023            11.54%             12.40%
Y2024            12.18%             11.71%
Y2025            13.24%             13.08%
Last Day         13.42%              8.00%
Last Week        10.43%              6.44%
Last Month       20.00%             25.69%
Last Qtr         13.24%             13.08%
Last Year        12.72%             11.32%
             gru_day gruRTN_day
period
Start       20170104   20170104
End         20250418   20260213
Avg            8.96%      8.73%
Sum           179.69     184.71
Std            7.02%      8.38%
T              57.15      47.92
IR              6.25       5.11
Y2017         10.64%     10.52%
Y2018          9.75%     10.37%
Y2019         10.13%     10.01%
Y2020          9.14%     10.09%
Y2021          5.84%      5.33%
Y2022          8.53%      9.17%
Y2023          8.39%      5.70%
Y2024          8.66%      8.88%
Y2025         11.04%      9.38%
Y2026            NaN      4.01%
Last Day       0.28%     -7.68%
Last Week     -0.84%     -7.57%
Last Month     8.87%     -0.33%
Last Qtr      12.12%      2.75%
Last Year      8.35%      8.46%
             gru_avg
period
Start       20170104
End         20250418
Avg            9.33%
Sum           187.18
Std            7.79%
T              53.64
IR              5.87
Y2017         10.81%
Y2018         10.93%
Y2019          9.61%
Y2020          8.64%
Y2021          5.98%
Y2022          9.05%
Y2023          9.75%
Y2024          9.67%
Y2025         10.11%
Last Day      -2.64%
Last Week     -1.93%
Last Month     7.63%
Last Qtr      10.95%
Last Year      9.31%

In [2]:
from src.res.factor.util.stats.aggregate import eval_period_ic_multi
df = eval_period_ic_multi(ic_tables)

In [3]:
df

,df_scores_v0,df_scores_v2,df_scores_v3,ht_master_combined,gru_day,gruRTN_day,gru_avg
period,,,,,,,
Start,20180102,20180102,20180102,20180102,20170104,20170104,20170104
End,20250402,20250402,20250402,20250402,20250418,20260213,20250418
Avg,12.47%,13.32%,13.66%,13.37%,8.96%,8.73%,9.33%
Sum,216.88,231.70,237.63,232.63,179.69,184.71,187.18
Std,7.97%,8.74%,8.21%,9.36%,7.02%,8.38%,7.79%
T,65.27,63.57,69.40,59.55,57.15,47.92,53.64
IR,7.67,7.47,8.15,6.99,6.25,5.11,5.87
Y2017,NaN,NaN,NaN,NaN,10.64%,10.52%,10.81%
Y2018,17.92%,18.97%,19.12%,17.62%,9.75%,10.37%,10.93%
Y2019,14.35%,15.83%,15.80%,14.15%,10.13%,10.01%,9.61%
Y2020,12.99%,13.79%,13.75%,13.91%,9.14%,10.09%,8.64%
Y2021,10.32%,10.94%,11.21%,11.10%,5.84%,5.33%,5.98%
Y2022,10.63%,11.87%,12.02%,12.65%,8.53%,9.17%,9.05%
Y2023,11.64%,12.01%,11.54%,12.40%,8.39%,5.70%,9.75%
Y2024,9.03%,9.54%,12.18%,11.71%,8.66%,8.88%,9.67%
Y2025,13.32%,13.49%,13.24%,13.08%,11.04%,9.38%,10.11%
Y2026,NaN,NaN,NaN,NaN,NaN,4.01%,NaN
Last Day,11.21%,14.53%,13.42%,8.00%,0.28%,-7.68%,-2.64%
Last Week,9.30%,11.40%,10.43%,6.44%,-0.84%,-7.57%,-1.93%
Last Month,18.29%,20.97%,20.00%,25.69%,8.87%,-0.33%,7.63%
Last Qtr,13.32%,13.49%,13.24%,13.08%,12.12%,2.75%,10.95%
Last Year,10.64%,10.28%,12.72%,11.32%,8.35%,8.46%,9.31%

In [9]:
path = model_account_summary()['df_scores_v0']
df = DB.load_df(path)
factor_stats = df.astype({'date' : 'int'}).query('submodel == "best"').groupby('date')['value'].mean().reset_index(drop = False).dropna()
eval_period_ic(factor_stats.rename(columns = {'value' : 'ic'}))

period
Start         20180102
End           20250402
Avg             12.47%
Sum             216.88
Std              7.97%
T                65.27
IR                7.67
Y2018           17.92%
Y2019           14.35%
Y2020           12.99%
Y2021           10.32%
Y2022           10.63%
Y2023           11.64%
Y2024            9.03%
Y2025           13.32%
Last Day        11.21%
Last Week        9.30%
Last Month      18.29%
Last Qtr        13.32%
Last Year       10.64%
Name: ic, dtype: object

In [1]:
from src.res.factor.util.classes.alpha_model import AlphaComposite , AlphaScreener

screener = AlphaScreener('gru_day_V1')
amodel = screener.get(20241231)

In [2]:
amodel.item().to_dataframe(indus = True)

       secid     alpha       indus
0          1  1.126028        bank
1          2  1.253377      estate
2          4  0.986078    software
3          6  1.044249      estate
4          7  0.795379      retail
...      ...       ...         ...
5176  920978  0.359580        auto
5177  920981  2.206729  electronic
5178  920982  0.554663      health
5179  920985  1.038696       power
5180  920992  0.164047      health

[5181 rows x 3 columns]

In [3]:
from src.res.factor.fmp.generator.revscreen import RevScreeningPortfolioCreatorConfig

config = RevScreeningPortfolioCreatorConfig.init_from()
config.get_screen_alpha(20241231)

  --> RevScreeningPortfolioCreatorConfig.init_from: no kwargs used

       secid     alpha       indus
0          1  1.126028        bank
1          2  1.253377      estate
2          4  0.986078    software
3          6  1.044249      estate
4          7  0.795379      retail
...      ...       ...         ...
5176  920978  0.359580        auto
5177  920981  2.206729  electronic
5178  920982  0.554663      health
5179  920985  1.038696       power
5180  920992  0.164047      health

[5181 rows x 3 columns]

In [ ]:
import subprocess
subprocess.run(['echo', '"hello"'], check=True)

hello

CompletedProcess(args='echo "hello"', returncode=0)

In [5]:
import subprocess
args = ['ping']
cmux_bin = 'cmux'
r = subprocess.run(
    [cmux_bin, *args],
    capture_output=True,
    text=True,
    timeout=2,
    stdin=subprocess.DEVNULL,
)

In [6]:
r

CompletedProcess(args=['cmux', 'ping'], returncode=1, stdout='', stderr='Error: Failed to write to socket\n')

In [4]:
from terminal_opener.macos.cmux import CmuxCli
CmuxCli.cmux_ping()

RuntimeError: cmux failed: Error: Failed to write to socket

In [3]:
from terminal_opener.macos.cmux.open import start_cmux
start_cmux()

RuntimeError: cmux failed: Error: Failed to write to socket

RuntimeError: cmux failed: Error: Failed to write to socket

In [ ]:
from src.proj import CALENDAR , DB 
start = 20200101
end = 20241231

dates = CALENDAR.range(start , end , 'td')
df = DB.loads('sellside', 'dongfang.l2_chars', dates = dates , accelerator = 'dask')
df

,date,secid,l2c0,l2c1,l2c2,l2c3,l2c4,twap,vwap,bwap,...,bamt8h_p5,samt8h_p5,aret8h,aret8h_p1,aret8h_p5,amtca,bopct_p1,bopct_p5,bopcth1_p1,bopcth1_p5
20200102,20200102,1,5.170533,-0.003904,1.072400,0.973690,-0.057844,16.837847,16.802659,16.799247,...,3.655721e+07,3.016089e+07,-0.059294,0.355907,0.711393,12613429.08,50.424712,51.806196,45.896762,48.540604
20200102,20200102,2,4.084804,0.183207,1.284276,1.020697,0.160532,32.947708,33.023155,33.019275,...,5.814658e+07,1.436228e+08,-0.674022,-0.612916,-3.066423,10881552.00,38.769563,44.875960,47.519704,50.824618
20200102,20200102,4,0.030807,-0.283523,1.653258,1.429564,0.034340,22.546706,22.486152,22.498289,...,6.916650e+05,3.213892e+06,-0.044773,-1.521296,-3.176931,614075.00,28.361788,39.645581,78.512581,66.412926
20200102,20200102,5,0.803120,0.558814,2.205219,2.183016,0.532615,3.137326,3.136475,3.134729,...,1.194456e+06,1.008486e+06,-0.318980,0.000000,-0.956939,353250.00,67.391042,55.323351,85.164693,68.655873
20200102,20200102,6,2.850461,-0.187019,1.615819,1.512321,-0.013689,5.405130,5.406967,5.407545,...,3.315738e+06,2.294550e+06,0.185701,-0.371058,0.000344,592920.00,38.681133,46.706779,43.938789,48.634441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5102,20241231,688799,0.117499,-0.606907,2.509321,2.328867,-0.347379,42.273386,42.225009,42.286815,...,1.227032e+06,1.229501e+06,0.215182,0.023892,0.071585,58632.00,16.594984,39.656249,NaN,52.757679
5103,20241231,688800,2.841288,-0.381414,2.609643,1.846047,-0.536761,50.882941,51.166661,51.214823,...,3.175559e+06,1.447925e+07,-0.557215,-0.360451,-1.551471,4881164.99,43.000628,43.043217,38.072955,40.309299
5104,20241231,688819,0.109285,0.099253,1.634580,1.437814,0.339325,27.490626,27.461015,27.475719,...,6.393427e+05,1.421560e+06,0.183925,0.036449,0.036410,2530017.34,42.732629,43.322205,80.448662,60.505173
5105,20241231,688981,3.600935,-0.273586,2.700302,2.259619,-0.372466,96.025350,96.178363,96.231482,...,2.256942e+08,1.806657e+08,0.063385,0.259703,-0.219798,91940361.60,35.958929,43.752408,33.309551,42.664565
5106,20241231,689009,0.055809,0.000624,1.518787,1.417188,-0.083305,47.852732,47.849371,47.858195,...,7.989949e+06,1.103034e+07,-0.442432,-0.587519,-0.105510,5552607.50,43.105170,47.168957,29.618246,45.187790

In [2]:
DB.loads('sellside', 'dongfang.l2_chars', dates = dates , accelerator = 'thread')

,date,secid,l2c0,l2c1,l2c2,l2c3,l2c4,twap,vwap,bwap,...,bamt8h_p5,samt8h_p5,aret8h,aret8h_p1,aret8h_p5,amtca,bopct_p1,bopct_p5,bopcth1_p1,bopcth1_p5
20200108,20200108,1,1.859320,-0.444646,1.201400,1.045367,-0.477771,16.783914,16.791322,16.803650,...,2.878288e+07,6.846058e+07,-0.180018,-0.719892,-2.339083,21683223.24,45.720239,42.049346,41.411921,43.701193
20200108,20200108,2,1.549941,-0.430353,1.083188,0.955691,-0.540770,31.517649,31.455731,31.449905,...,6.314391e+07,3.815152e+07,0.379627,0.978263,2.081662,17560889.28,50.043624,50.468336,42.980705,47.061631
20200108,20200108,4,0.459559,-0.014735,1.980576,1.450941,0.134714,22.226745,22.300409,22.272994,...,6.573800e+04,1.703480e+05,-0.458086,0.000000,-0.091492,228690.00,52.522842,53.797654,44.293698,53.852538
20200108,20200108,5,5.173031,-0.125369,2.207719,1.915392,-0.060499,3.192951,3.201236,3.203253,...,3.585820e+05,2.179117e+06,-0.632914,-0.631912,-0.314955,668493.00,47.645785,49.941567,48.518043,48.937960
20200108,20200108,6,1.557274,-0.632114,1.950668,1.848044,-0.649619,5.432309,5.429410,5.435373,...,1.697900e+06,6.952856e+05,0.000000,0.000000,-0.555386,880187.00,40.887775,43.395795,22.877856,38.541606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5102,20241231,688799,0.117499,-0.606907,2.509321,2.328867,-0.347379,42.273386,42.225009,42.286815,...,1.227032e+06,1.229501e+06,0.215182,0.023892,0.071585,58632.00,16.594984,39.656249,NaN,52.757679
5103,20241231,688800,2.841288,-0.381414,2.609643,1.846047,-0.536761,50.882941,51.166661,51.214823,...,3.175559e+06,1.447925e+07,-0.557215,-0.360451,-1.551471,4881164.99,43.000628,43.043217,38.072955,40.309299
5104,20241231,688819,0.109285,0.099253,1.634580,1.437814,0.339325,27.490626,27.461015,27.475719,...,6.393427e+05,1.421560e+06,0.183925,0.036449,0.036410,2530017.34,42.732629,43.322205,80.448662,60.505173
5105,20241231,688981,3.600935,-0.273586,2.700302,2.259619,-0.372466,96.025350,96.178363,96.231482,...,2.256942e+08,1.806657e+08,0.063385,0.259703,-0.219798,91940361.60,35.958929,43.752408,33.309551,42.664565
5106,20241231,689009,0.055809,0.000624,1.518787,1.417188,-0.083305,47.852732,47.849371,47.858195,...,7.989949e+06,1.103034e+07,-0.442432,-0.587519,-0.105510,5552607.50,43.105170,47.168957,29.618246,45.187790

In [3]:
DB.loads('sellside', 'dongfang.l2_chars', dates = dates , accelerator = 'polars')

,secid,l2c0,l2c1,l2c2,l2c3,l2c4,twap,vwap,bwap,bwap_p5,...,samt8h_p5,aret8h,aret8h_p1,aret8h_p5,amtca,bopct_p1,bopct_p5,bopcth1_p1,bopcth1_p5,date
0,1,5.170533,-0.003904,1.072400,0.973690,-0.057844,16.837847,16.802659,16.799247,16.802503,...,3.016089e+07,-0.059294,0.355907,0.711393,12613429.08,50.424712,51.806196,45.896762,48.540604,20200102
1,2,4.084804,0.183207,1.284276,1.020697,0.160532,32.947708,33.023155,33.019275,33.046306,...,1.436228e+08,-0.674022,-0.612916,-3.066423,10881552.00,38.769563,44.875960,47.519704,50.824618,20200102
2,4,0.030807,-0.283523,1.653258,1.429564,0.034340,22.546706,22.486152,22.498289,22.504771,...,3.213892e+06,-0.044773,-1.521296,-3.176931,614075.00,28.361788,39.645581,78.512581,66.412926,20200102
3,5,0.803120,0.558814,2.205219,2.183016,0.532615,3.137326,3.136475,3.134729,3.133499,...,1.008486e+06,-0.318980,0.000000,-0.956939,353250.00,67.391042,55.323351,85.164693,68.655873,20200102
4,6,2.850461,-0.187019,1.615819,1.512321,-0.013689,5.405130,5.406967,5.407545,5.407686,...,2.294550e+06,0.185701,-0.371058,0.000344,592920.00,38.681133,46.706779,43.938789,48.634441,20200102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5588342,688799,0.117499,-0.606907,2.509321,2.328867,-0.347379,42.273386,42.225009,42.286815,42.241894,...,1.229501e+06,0.215182,0.023892,0.071585,58632.00,16.594984,39.656249,NaN,52.757679,20241231
5588343,688800,2.841288,-0.381414,2.609643,1.846047,-0.536761,50.882941,51.166661,51.214823,51.407721,...,1.447925e+07,-0.557215,-0.360451,-1.551471,4881164.99,43.000628,43.043217,38.072955,40.309299,20241231
5588344,688819,0.109285,0.099253,1.634580,1.437814,0.339325,27.490626,27.461015,27.475719,27.423002,...,1.421560e+06,0.183925,0.036449,0.036410,2530017.34,42.732629,43.322205,80.448662,60.505173,20241231
5588345,688981,3.600935,-0.273586,2.700302,2.259619,-0.372466,96.025350,96.178363,96.231482,96.215483,...,1.806657e+08,0.063385,0.259703,-0.219798,91940361.60,35.958929,43.752408,33.309551,42.664565,20241231
5588346,689009,0.055809,0.000624,1.518787,1.417188,-0.083305,47.852732,47.849371,47.858195,47.829625,...,1.103034e+07,-0.442432,-0.587519,-0.105510,5552607.50,43.105170,47.168957,29.618246,45.187790,20241231

In [4]:
DB.loads('sellside', 'dongfang.l2_chars', dates = dates , accelerator = 'polars_thread')

,secid,l2c0,l2c1,l2c2,l2c3,l2c4,twap,vwap,bwap,bwap_p5,...,samt8h_p5,aret8h,aret8h_p1,aret8h_p5,amtca,bopct_p1,bopct_p5,bopcth1_p1,bopcth1_p5,date
0,1,2.309733,0.031790,1.012716,0.841579,0.030661,16.814186,16.835403,16.831354,16.835330,...,5.192233e+07,0.235849,0.765660,-1.411138,8569501.15,54.403776,53.185565,45.496060,49.977673,20200113
1,2,2.458431,-0.307440,0.940326,0.846133,-0.301987,31.540629,31.529156,31.534116,31.546212,...,2.942579e+07,0.379507,0.189204,0.189125,16448256.00,45.817295,48.456070,46.473844,48.573815,20200113
2,4,0.281294,0.063725,1.985651,1.690532,0.111967,22.992855,22.999400,22.997900,23.001587,...,3.053554e+06,-0.476294,-0.776365,-0.560039,1321922.00,50.200325,50.737325,48.535114,52.819975,20200113
3,5,0.008239,-0.358024,2.526663,2.500968,0.085425,3.149435,3.148194,3.149475,3.150718,...,3.447560e+05,0.316957,0.316957,0.002003,662652.00,38.935177,41.814377,35.212520,35.553729,20200113
4,6,0.246622,0.463147,1.839752,1.760141,-0.122006,5.492315,5.492792,5.486845,5.483689,...,3.773320e+06,0.362977,-1.268281,-1.448950,2552648.00,49.772277,47.502807,56.078483,47.160380,20200113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5588342,688799,0.117499,-0.606907,2.509321,2.328867,-0.347379,42.273386,42.225009,42.286815,42.241894,...,1.229501e+06,0.215182,0.023892,0.071585,58632.00,16.594984,39.656249,NaN,52.757679,20241231
5588343,688800,2.841288,-0.381414,2.609643,1.846047,-0.536761,50.882941,51.166661,51.214823,51.407721,...,1.447925e+07,-0.557215,-0.360451,-1.551471,4881164.99,43.000628,43.043217,38.072955,40.309299,20241231
5588344,688819,0.109285,0.099253,1.634580,1.437814,0.339325,27.490626,27.461015,27.475719,27.423002,...,1.421560e+06,0.183925,0.036449,0.036410,2530017.34,42.732629,43.322205,80.448662,60.505173,20241231
5588345,688981,3.600935,-0.273586,2.700302,2.259619,-0.372466,96.025350,96.178363,96.231482,96.215483,...,1.806657e+08,0.063385,0.259703,-0.219798,91940361.60,35.958929,43.752408,33.309551,42.664565,20241231
5588346,689009,0.055809,0.000624,1.518787,1.417188,-0.083305,47.852732,47.849371,47.858195,47.829625,...,1.103034e+07,-0.442432,-0.587519,-0.105510,5552607.50,43.105170,47.168957,29.618246,45.187790,20241231

In [ ]:
from src.data import DataBlock

from src.proj import CALENDAR , DB 
start = 20200101
end = 20241231

dates = CALENDAR.range(start , end , 'td')

def test1():
    dfpl = DB.loads_pl('sellside', 'dongfang.l2_chars', dates = dates[50:100])
    block = DataBlock.from_polars(dfpl)
    return block

def test2():
    df = DB.loads('sellside', 'dongfang.l2_chars', dates = dates[50:100])
    block = DataBlock.from_pandas(df)
    return block

In [3]:
DataBlock.load_raw('sellside', 'dongfang.l2_chars', dates = dates[50:100])

DataBlock(values=torch.Size([3843, 50, 1, 100]),secid=[     1      2      4 ... 688566 688588 688598],date=[20200320 20200323 20200324 20200325 20200326 20200327 20200330 20200331
 20200401 20200402 20200403 20200407 20200408 20200409 20200410 20200413
 20200414 20200415 20200416 20200417 20200420 20200421 20200422 20200423
 20200424 20200427 20200428 20200429 20200430 20200506 20200507 20200508
 20200511 20200512 20200513 20200514 20200515 20200518 20200519 20200520
 20200521 20200522 20200525 20200526 20200527 20200528 20200529 20200601
 20200602 20200603],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [4]:
DataBlock.load_from_db_pandas('sellside', 'dongfang.l2_chars', dates = dates[50:100])

DataBlock(values=torch.Size([3843, 50, 1, 100]),secid=[     1      2      4 ... 688566 688588 688598],date=[20200320 20200323 20200324 20200325 20200326 20200327 20200330 20200331
 20200401 20200402 20200403 20200407 20200408 20200409 20200410 20200413
 20200414 20200415 20200416 20200417 20200420 20200421 20200422 20200423
 20200424 20200427 20200428 20200429 20200430 20200506 20200507 20200508
 20200511 20200512 20200513 20200514 20200515 20200518 20200519 20200520
 20200521 20200522 20200525 20200526 20200527 20200528 20200529 20200601
 20200602 20200603],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [2]:
test1()

DataBlock(values=torch.Size([3843, 50, 1, 100]),secid=[     1      2      4 ... 688566 688588 688598],date=[20200320 20200323 20200324 20200325 20200326 20200327 20200330 20200331
 20200401 20200402 20200403 20200407 20200408 20200409 20200410 20200413
 20200414 20200415 20200416 20200417 20200420 20200421 20200422 20200423
 20200424 20200427 20200428 20200429 20200430 20200506 20200507 20200508
 20200511 20200512 20200513 20200514 20200515 20200518 20200519 20200520
 20200521 20200522 20200525 20200526 20200527 20200528 20200529 20200601
 20200602 20200603],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [3]:
test2()

DataBlock(values=torch.Size([3843, 50, 1, 100]),secid=[     1      2      4 ... 688566 688588 688598],date=[20200320 20200323 20200324 20200325 20200326 20200327 20200330 20200331
 20200401 20200402 20200403 20200407 20200408 20200409 20200410 20200413
 20200414 20200415 20200416 20200417 20200420 20200421 20200422 20200423
 20200424 20200427 20200428 20200429 20200430 20200506 20200507 20200508
 20200511 20200512 20200513 20200514 20200515 20200518 20200519 20200520
 20200521 20200522 20200525 20200526 20200527 20200528 20200529 20200601
 20200602 20200603],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [1]:

import polars as pl
import torch

from src.proj import CALENDAR , DB , Logger

start = 20200101
end = 20241231

dates = CALENDAR.range(start , end , 'td')
dfpl = DB.loads_pl('sellside', 'dongfang.l2_chars', dates = dates[50:100])

with Logger.Profiler('polars to tensor') as pbar:
    df = dfpl

    # 1. Define the unique keys (keep these eager for the shape)
    unique_items = df["secid"].unique().sort()
    unique_dates = df["date"].unique().sort()
    feature_cols = [c for c in df.columns if c not in ["secid", "date"]]

    # 2. Use the Lazy API for the heavy lifting
    # This creates a "Plan" that Polars will optimize before running
    grid_lazy = unique_items.to_frame().join(unique_dates.to_frame(), how="cross").lazy()
    tensor_ready_df = (
        grid_lazy
        .join(df.lazy(), on=["secid", "date"], how="left")
        .sort(["secid", "date"]) # Vital for the reshape to work
        .select(feature_cols)
        .collect()
    )

    I, D, F = unique_items.len(), unique_dates.len(), len(feature_cols)
    tensor = torch.from_numpy(tensor_ready_df.to_numpy()).reshape(I, D, F)

Profiler(polars to tensor) start ...
Profiler(polars to tensor) finished! Cost <1 Sec
**Profile result saved to /Users/mengkjin/workspace/learndl/logs/profiler/polars_to_tensor.csv

      type                 name               ncalls   cumtime    tottime    percall                        where
0   function                         wrapper      4   8.240e-02  3.000e-04  2.060e-02  "/.venv/lib/python3.12/site-packages/polars/_u...
1   function                         wrapper      4   8.220e-02  0.000e+00  2.055e-02  "/.venv/lib/python3.12/site-packages/polars/la...
2   function                         collect      4   8.220e-02  8.220e-02  2.055e-02  "/.venv/lib/python3.12/site-packages/polars/la...
3   function                        to_numpy      1   2.490e-02  2.490e-02  2.490e-02  "/.venv/lib/python3.12/site-packages/polars/da...
4   function                         wrapper      2   1.900e-03  0.000e+00  9.500e-04  "/.venv/lib/python3.12/site-packages/polars/se...
5   function                      select_seq      2   1.800e-03  0.000e+00  9.000e-04  "/.venv/lib/python3.12/site-packages/polars/da...
6   function                            join      1   7.000e-04  0.000e+00  7.000e-04  "/.venv/lib/python3.12/site-packages/polars/da...
7   function                         wrapper      3   7.000e-04  0.000e+00  2.333e-04  "/.venv/lib/python3.12/site-packages/polars/_u...
8   function                  _handle_events      1   2.000e-04  0.000e+00  2.000e-04  "/.venv/lib/python3.12/site-packages/zmq/event...
9   function                          select      1   2.000e-04  0.000e+00  2.000e-04  "/.venv/lib/python3.12/site-packages/polars/la...
10  function                  _handle_events      1   2.000e-04  0.000e+00  2.000e-04  "/.venv/lib/python3.12/site-packages/tornado/p...
11  function        _parse_positional_inputs      5   2.000e-04  0.000e+00  4.000e-05  "/.venv/lib/python3.12/site-packages/polars/_u...
12  function  parse_into_list_of_expressions      5   2.000e-04  0.000e+00  4.000e-05  "/.venv/lib/python3.12/site-packages/polars/_u...
13  function                            _run      1   2.000e-04  0.000e+00  2.000e-04  "/Library/Frameworks/Python.framework/Versions...
14  function                    _handle_recv      1   1.000e-04  0.000e+00  1.000e-04  "/.venv/lib/python3.12/site-packages/zmq/event...
15  function                     __getattr__      2   1.000e-04  0.000e+00  5.000e-05  "/.venv/lib/python3.12/site-packages/zmq/sugar...
16  function                   _get_attr_opt      2   1.000e-04  0.000e+00  5.000e-05  "/.venv/lib/python3.12/site-packages/zmq/sugar...
17  function                          stdout      1   1.000e-04  0.000e+00  1.000e-04                     "/src/proj/core/output.py",132
18  function                      new_stdout      1   1.000e-04  0.000e+00  1.000e-04                       "/src/proj/log/logger.py",34
19  function           parse_into_expression    106   1.000e-04  0.000e+00  9.434e-07  "/.venv/lib/python3.12/site-packages/polars/_u...

In [ ]:
from src.proj import CALENDAR , DB 
start = 20160101
end = 20241231

dates = CALENDAR.range(start , end , 'td')
df = DB.loads_pl('sellside', 'dongfang.l2_chars', dates = dates)
df

shape: (8_674_987, 102)
┌────────┬───────────┬───────────┬───────────┬───┬───────────┬────────────┬────────────┬──────────┐
│ secid  ┆ l2c0      ┆ l2c1      ┆ l2c2      ┆ … ┆ bopct_p5  ┆ bopcth1_p1 ┆ bopcth1_p5 ┆ date     │
│ ---    ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---      │
│ i64    ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64        ┆ f64        ┆ i32      │
╞════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪══════════╡
│ 1      ┆ 1.420385  ┆ -0.756812 ┆ 9.2988    ┆ … ┆ 36.034314 ┆ 24.146402  ┆ 36.034314  ┆ 20160107 │
│ 4      ┆ 1.201923  ┆ -0.705281 ┆ 3.793876  ┆ … ┆ 37.54434  ┆ 27.611162  ┆ 37.54434   ┆ 20160107 │
│ 5      ┆ 3.261267  ┆ -0.577171 ┆ 3.735842  ┆ … ┆ 44.329646 ┆ 43.20142   ┆ 44.329646  ┆ 20160107 │
│ 6      ┆ 6.297074  ┆ -0.759183 ┆ 5.227989  ┆ … ┆ 39.813272 ┆ 30.600196  ┆ 39.813272  ┆ 20160107 │
│ 8      ┆ 13.008543 ┆ -0.73739  ┆ 10.983805 ┆ … ┆ 45.215591 ┆ 45.675862  ┆ 45.215591  ┆ 20160107 │
│ …      ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …          ┆ …          ┆ …        │
│ 688799 ┆ 0.117499  ┆ -0.606907 ┆ 2.509321  ┆ … ┆ 39.656249 ┆ null       ┆ 52.757679  ┆ 20241231 │
│ 688800 ┆ 2.841288  ┆ -0.381414 ┆ 2.609643  ┆ … ┆ 43.043217 ┆ 38.072955  ┆ 40.309299  ┆ 20241231 │
│ 688819 ┆ 0.109285  ┆ 0.099253  ┆ 1.63458   ┆ … ┆ 43.322205 ┆ 80.448662  ┆ 60.505173  ┆ 20241231 │
│ 688981 ┆ 3.600935  ┆ -0.273586 ┆ 2.700302  ┆ … ┆ 43.752408 ┆ 33.309551  ┆ 42.664565  ┆ 20241231 │
│ 689009 ┆ 0.055809  ┆ 0.000624  ┆ 1.518787  ┆ … ┆ 47.168957 ┆ 29.618246  ┆ 45.18779   ┆ 20241231 │
└────────┴───────────┴───────────┴───────────┴───┴───────────┴────────────┴────────────┴──────────┘

In [1]:
from src.data.preprocess.processors import PrePro_dfl2
calc = PrePro_dfl2()
calc.pre_process(start = 20240101 , end = 20241231)

DataBlock(values=torch.Size([5170, 242, 1, 100]),secid=[     1      2      4 ... 688819 688981 689009],date=[20240102 20240103 20240104 20240105 20240108 20240109 20240110 20240111
 20240112 20240115 20240116 20240117 20240118 20240119 20240122 20240123
 20240124 20240125 20240126 20240129 20240130 20240131 20240201 20240202
 20240205 20240206 20240207 20240208 20240219 20240220 20240221 20240222
 20240223 20240226 20240227 20240228 20240229 20240301 20240304 20240305
 20240306 20240307 20240308 20240311 20240312 20240313 20240314 20240315
 20240318 20240319 20240320 20240321 20240322 20240325 20240326 20240327
 20240328 20240329 20240401 20240402 20240403 20240408 20240409 20240410
 20240411 20240412 20240415 20240416 20240417 20240418 20240419 20240422
 20240423 20240424 20240425 20240426 20240429 20240430 20240506 20240507
 20240508 20240509 20240510 20240513 20240514 20240515 20240516 20240517
 20240520 20240521 20240522 20240523 20240524 20240527 20240528 20240529
 20240530 20240531 20240603 20240604 20240605 20240606 20240607 20240611
 20240612 20240613 20240614 20240617 20240618 20240619 20240620 20240621
 20240624 20240625 20240626 20240627 20240628 20240701 20240702 20240703
 20240704 20240705 20240708 20240709 20240710 20240711 20240712 20240715
 20240716 20240717 20240718 20240719 20240722 20240723 20240724 20240725
 20240726 20240729 20240730 20240731 20240801 20240802 20240805 20240806
 20240807 20240808 20240809 20240812 20240813 20240814 20240815 20240816
 20240819 20240820 20240821 20240822 20240823 20240826 20240827 20240828
 20240829 20240830 20240902 20240903 20240904 20240905 20240906 20240909
 20240910 20240911 20240912 20240913 20240918 20240919 20240920 20240923
 20240924 20240925 20240926 20240927 20240930 20241008 20241009 20241010
 20241011 20241014 20241015 20241016 20241017 20241018 20241021 20241022
 20241023 20241024 20241025 20241028 20241029 20241030 20241031 20241101
 20241104 20241105 20241106 20241107 20241108 20241111 20241112 20241113
 20241114 20241115 20241118 20241119 20241120 20241121 20241122 20241125
 20241126 20241127 20241128 20241129 20241202 20241203 20241204 20241205
 20241206 20241209 20241210 20241211 20241212 20241213 20241216 20241217
 20241218 20241219 20241220 20241223 20241224 20241225 20241226 20241227
 20241230 20241231],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [2]:
from src.proj import CALENDAR

In [3]:
CALENDAR.range(20251104 , 20251106)

array([20251104, 20251105, 20251106])

In [1]:
from src.data.preprocess.processors import PrePro_quality
from src.proj import Proj
with Proj.vb.WithVB(10):
    pre = PrePro_quality('predict')
    pre.update()

Project Verbosity Changed from 3 to 10

  --> Update Preprocess [QUALITY] for predicting start...
      --> Timer([quality] dumped loading) start ...
      --> Timer([quality] dumped loading) finished! Cost <1 Sec
        --> Timer([quality] blocks loading) start ...
            --> Timer(factor blocks reading [fundamental , quality]) start ...
            --> Timer(factor blocks reading [fundamental , quality]) finished! Cost <1 Sec
            --> Timer(factor blocks merging (16 factors)) start ...
            --> Timer(factor blocks merging (16 factors)) finished! Cost <1 Sec
        --> Timer([quality] blocks loading) finished! Cost 1.3 Sec
        --> Timer([quality] blocks process) start ...
        --> Timer([quality] blocks process) finished! Cost <1 Sec
        --> Timer([quality] blocks masking) start ...
        --> Timer([quality] blocks masking) finished! Cost <1 Sec
      --> Timer([quality] blocks merging) start ...
      --> Timer([quality] blocks merging) finished! Cost <1 Sec
      --> Timer([quality] blocks dumping) start ...
      --> Timer([quality] blocks dumping) finished! Cost <1 Sec
    --> Success : Update Preprocess [QUALITY] for predicting  (20241119~20250418(85days)) finished! Cost 1.5 Sec

Project Verbosity Changed from 10 to 3

In [4]:
PrePro_quality.category1

'quality'

In [3]:
5123 * 35 * 9 / 12895029

0.1251447360064099

In [21]:
import numpy as np
np.random.randint(1000000)

910719

In [2]:
from src.res.factor.calculator import StockFactorHierarchy
hier = StockFactorHierarchy()
calc = hier.get_factor('df_scores_v0')

In [3]:
calc.Factor(dates = [20250417])

StockFactor(normalized=True,names=['df_scores_v0'],dates=1(20250417-20250417))

In [27]:
import polars as pl
df = pl.read_ipc('/Users/mengkjin/workspace/learndl/models/st/nn@gru@gru_l2/snapshot/pred_recorder/preds/0.20241101.20241104.20241211.feather')
df.collect_schema().names()

Could not memory_map compressed IPC file, defaulting to normal read. Toggle off 'memory_map' to silence this warning.

['model_num',
 'model_date',
 'submodel',
 'batch_idx',
 'secid',
 'date',
 'pred',
 'label']

In [24]:
[f'abc'
f'cde']

['abccde']

In [5]:
import pandas as pd
df = pd.read_feather('/Users/mengkjin/workspace/learndl/models/st/nn@gru@gru_l2/snapshot/pred_recorder/preds/0.20241101.20241104.20241211.feather')
df.groupby(['model_date' , 'submodel' , 'secid' , 'date'])[['pred' , 'label']].mean().reset_index()

      model_date submodel   secid      date      pred     label
0       20241101     best      55  20241104 -1.101364  1.297629
1       20241101     best      55  20241105 -1.238857  0.736876
2       20241101     best      55  20241106 -1.480604  0.544954
3       20241101     best      55  20241107 -2.041470  0.596318
4       20241101     best      55  20241108 -2.698923  0.754759
...          ...      ...     ...       ...       ...       ...
5180    20241101     best  688800  20241205 -2.404348  3.476214
5181    20241101     best  688800  20241206 -2.590947  3.489037
5182    20241101     best  688800  20241209 -2.365587  3.603701
5183    20241101     best  688800  20241210 -2.406508  3.752459
5184    20241101     best  688800  20241211 -2.411360  3.930509

[5185 rows x 6 columns]

In [1]:
from src.data.preprocess.processors import PrePro_dfl2
calc = PrePro_dfl2()
calc.pre_process(start = 20240101 , end = 20241231)

DataBlock(values=torch.Size([5218, 242, 1, 100]),secid=[     1      2      4 ... 688819 688981 689009],date=[20240102 20240103 20240104 20240105 20240108 20240109 20240110 20240111
 20240112 20240115 20240116 20240117 20240118 20240119 20240122 20240123
 20240124 20240125 20240126 20240129 20240130 20240131 20240201 20240202
 20240205 20240206 20240207 20240208 20240219 20240220 20240221 20240222
 20240223 20240226 20240227 20240228 20240229 20240301 20240304 20240305
 20240306 20240307 20240308 20240311 20240312 20240313 20240314 20240315
 20240318 20240319 20240320 20240321 20240322 20240325 20240326 20240327
 20240328 20240329 20240401 20240402 20240403 20240408 20240409 20240410
 20240411 20240412 20240415 20240416 20240417 20240418 20240419 20240422
 20240423 20240424 20240425 20240426 20240429 20240430 20240506 20240507
 20240508 20240509 20240510 20240513 20240514 20240515 20240516 20240517
 20240520 20240521 20240522 20240523 20240524 20240527 20240528 20240529
 20240530 20240531 20240603 20240604 20240605 20240606 20240607 20240611
 20240612 20240613 20240614 20240617 20240618 20240619 20240620 20240621
 20240624 20240625 20240626 20240627 20240628 20240701 20240702 20240703
 20240704 20240705 20240708 20240709 20240710 20240711 20240712 20240715
 20240716 20240717 20240718 20240719 20240722 20240723 20240724 20240725
 20240726 20240729 20240730 20240731 20240801 20240802 20240805 20240806
 20240807 20240808 20240809 20240812 20240813 20240814 20240815 20240816
 20240819 20240820 20240821 20240822 20240823 20240826 20240827 20240828
 20240829 20240830 20240902 20240903 20240904 20240905 20240906 20240909
 20240910 20240911 20240912 20240913 20240918 20240919 20240920 20240923
 20240924 20240925 20240926 20240927 20240930 20241008 20241009 20241010
 20241011 20241014 20241015 20241016 20241017 20241018 20241021 20241022
 20241023 20241024 20241025 20241028 20241029 20241030 20241031 20241101
 20241104 20241105 20241106 20241107 20241108 20241111 20241112 20241113
 20241114 20241115 20241118 20241119 20241120 20241121 20241122 20241125
 20241126 20241127 20241128 20241129 20241202 20241203 20241204 20241205
 20241206 20241209 20241210 20241211 20241212 20241213 20241216 20241217
 20241218 20241219 20241220 20241223 20241224 20241225 20241226 20241227
 20241230 20241231],feature=['l2c0' 'l2c1' 'l2c2' 'l2c3' 'l2c4' 'twap' 'vwap' 'bwap' 'bwap_p5'
 'bwap_p1' 'swap' 'swap_p5' 'swap_p1' 'amtoa' 'bamt' 'samt' 'bamt_p1'
 'samt_p1' 'bamt_p5' 'samt_p5' 'aret' 'aret_p1' 'aret_p5' 'bamt1h'
 'samt1h' 'bamt1h_p1' 'samt1h_p1' 'bamt1h_p5' 'samt1h_p5' 'aret1h'
 'aret1h_p1' 'aret1h_p5' 'bamt2h' 'samt2h' 'bamt2h_p1' 'samt2h_p1'
 'bamt2h_p5' 'samt2h_p5' 'aret2h' 'aret2h_p1' 'aret2h_p5' 'bamt3h'
 'samt3h' 'bamt3h_p1' 'samt3h_p1' 'bamt3h_p5' 'samt3h_p5' 'aret3h'
 'aret3h_p1' 'aret3h_p5' 'bamt4h' 'samt4h' 'bamt4h_p1' 'samt4h_p1'
 'bamt4h_p5' 'samt4h_p5' 'aret4h' 'aret4h_p1' 'aret4h_p5' 'bamt5h'
 'samt5h' 'bamt5h_p1' 'samt5h_p1' 'bamt5h_p5' 'samt5h_p5' 'aret5h'
 'aret5h_p1' 'aret5h_p5' 'bamt6h' 'samt6h' 'bamt6h_p1' 'samt6h_p1'
 'bamt6h_p5' 'samt6h_p5' 'aret6h' 'aret6h_p1' 'aret6h_p5' 'bamt7h'
 'samt7h' 'bamt7h_p1' 'samt7h_p1' 'bamt7h_p5' 'samt7h_p5' 'aret7h'
 'aret7h_p1' 'aret7h_p5' 'bamt8h' 'samt8h' 'bamt8h_p1' 'samt8h_p1'
 'bamt8h_p5' 'samt8h_p5' 'aret8h' 'aret8h_p1' 'aret8h_p5' 'amtca'
 'bopct_p1' 'bopct_p5' 'bopcth1_p1' 'bopcth1_p5'])

In [6]:
WINDOW = 250

# 2. Identify the columns to transform (exclude index columns)
cols_to_z = [c for c in df.columns if c not in ["secid", "date"]]

# 3. Apply rolling z-score partitioned by item
# min_periods=1 allows calculation starting from the very first row
df_z = df.with_columns([
    ((pl.col(c) - pl.col(c).rolling_mean(window_size=WINDOW, min_samples=120).over("secid")) / 
     pl.col(c).rolling_std(window_size=WINDOW, min_samples=120).over("secid")).alias(c)
    for c in cols_to_z
])

In [15]:
df_z.filter(pl.col('date') == 20241231)

shape: (5_107, 102)
┌────────┬───────────┬───────────┬───────────┬───┬───────────┬────────────┬────────────┬──────────┐
│ secid  ┆ l2c0      ┆ l2c1      ┆ l2c2      ┆ … ┆ bopct_p5  ┆ bopcth1_p1 ┆ bopcth1_p5 ┆ date     │
│ ---    ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---      │
│ i64    ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64        ┆ f64        ┆ i32      │
╞════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪══════════╡
│ 1      ┆ 1.228757  ┆ -0.183943 ┆ 4.257936  ┆ … ┆ -0.858653 ┆ 0.463759   ┆ 0.433038   ┆ 20241231 │
│ 2      ┆ -0.935568 ┆ -0.442009 ┆ 0.346512  ┆ … ┆ -0.0565   ┆ 0.210665   ┆ 0.062929   ┆ 20241231 │
│ 4      ┆ -0.540429 ┆ 0.367127  ┆ -0.282954 ┆ … ┆ 0.65079   ┆ 0.359449   ┆ 0.51988    ┆ 20241231 │
│ 6      ┆ 0.010538  ┆ -0.634613 ┆ -0.6219   ┆ … ┆ -0.873709 ┆ 0.284993   ┆ -0.022201  ┆ 20241231 │
│ 7      ┆ -0.756338 ┆ -0.770774 ┆ 0.288362  ┆ … ┆ -0.875928 ┆ -0.259267  ┆ 0.097347   ┆ 20241231 │
│ …      ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …          ┆ …          ┆ …        │
│ 688799 ┆ -0.355769 ┆ -1.874933 ┆ -0.465909 ┆ … ┆ -1.696357 ┆ null       ┆ 0.117742   ┆ 20241231 │
│ 688800 ┆ -0.329784 ┆ -1.75272  ┆ -0.037863 ┆ … ┆ -1.20207  ┆ -0.711793  ┆ -1.369835  ┆ 20241231 │
│ 688819 ┆ -0.481545 ┆ 0.723691  ┆ 0.45104   ┆ … ┆ -1.134063 ┆ 1.912459   ┆ 1.412159   ┆ 20241231 │
│ 688981 ┆ -0.036724 ┆ -1.32044  ┆ 0.513374  ┆ … ┆ -0.942775 ┆ -1.06688   ┆ -0.749553  ┆ 20241231 │
│ 689009 ┆ -0.874233 ┆ 0.232923  ┆ -0.500973 ┆ … ┆ -0.537835 ┆ -1.687308  ┆ -0.696833  ┆ 20241231 │
└────────┴───────────┴───────────┴───────────┴───┴───────────┴────────────┴────────────┴──────────┘

In [ ]:
from src.data.crawler.announcement.agent import AnnouncementAgent
AnnouncementAgent.prepare_proxies()

*********************************************** Prepare Proxies Start at 2026-03-24 15:25:09 ***********************************************

26-03-24 15:25:09|INFO      |: Prepare proxies for https://www.sse.com.cn
26-03-24 15:25:09|INFO      |: Get working proxies for https://www.sse.com.cn

  --> Timer(Quick Verification (4.0s) for http://www.example.com, 10 in 3 passed) finished! Cost 4.0 Sec
  --> Timer(Final Verification (8.0s) for https://www.sse.com.cn, 3 in 2 passed) finished! Cost 7.0 Sec
  --> Timer(Load candidates, 10 loaded, 2 passed) finished! Cost 11.0 Sec
  --> Timer(Round 1 Find candidates, 204 found) finished! Cost 5.7 Sec
  --> Timer(Round 1 Quick Verification (4.0s) for http://www.example.com, 211 in 34 passed) finished! Cost 14.2 Sec
  --> Timer(Round 1 Final Verification (8.0s) for https://www.sse.com.cn, 34 in 5 passed) finished! Cost 8.0 Sec
  --> Timer(Round 2 Find candidates, 204 found) finished! Cost 5.4 Sec
  --> Timer(Round 2 Quick Verification (4.0s) for http://www.example.com, 198 in 32 passed) finished! Cost 15.2 Sec
  --> Timer(Round 2 Final Verification (8.0s) for https://www.sse.com.cn, 32 in 2 passed) finished! Cost 8.0 Sec
  --> Timer(Round 3 Find candidates, 205 found) finished! Cost 5.5 Sec
  --> Timer(Round 3 Quick Verification (4.0s) for http://www.example.com, 197 in 21 passed) finished! Cost 15.7 Sec
  --> Timer(Round 3 Final Verification (8.0s) for https://www.sse.com.cn, 21 in 0 passed) finished! Cost 8.0 Sec

26-03-24 15:26:45|INFO      |: Prepare proxies for https://www.szse.cn
26-03-24 15:26:45|INFO      |: Get working proxies for https://www.szse.cn

  --> Timer(Quick Verification (4.0s) for http://www.example.com, 11 in 6 passed) finished! Cost 4.0 Sec
  --> Timer(Final Verification (8.0s) for https://www.szse.cn, 6 in 4 passed) finished! Cost 6.2 Sec
  --> Timer(Load candidates, 11 loaded, 4 passed) finished! Cost 10.2 Sec
  --> Timer(Round 1 Find candidates, 205 found) finished! Cost 5.6 Sec
  --> Timer(Round 1 Quick Verification (4.0s) for http://www.example.com, 210 in 22 passed) finished! Cost 16.0 Sec
  --> Timer(Round 1 Final Verification (8.0s) for https://www.szse.cn, 22 in 3 passed) finished! Cost 8.0 Sec
  --> Timer(Round 2 Find candidates, 205 found) finished! Cost 8.4 Sec
  --> Timer(Round 2 Quick Verification (4.0s) for http://www.example.com, 199 in 16 passed) finished! Cost 16.0 Sec
  --> Timer(Round 2 Final Verification (8.0s) for https://www.szse.cn, 16 in 0 passed) finished! Cost 6.3 Sec
  --> Timer(Round 3 Find candidates, 205 found) finished! Cost 5.7 Sec
  --> Timer(Round 3 Quick Verification (4.0s) for http://www.example.com, 199 in 21 passed) finished! Cost 16.0 Sec
  --> Timer(Round 3 Final Verification (8.0s) for https://www.szse.cn, 21 in 0 passed) finished! Cost 8.0 Sec

26-03-24 15:28:26|INFO      |: Prepare proxies for https://www.bse.cn
26-03-24 15:28:26|INFO      |: Get working proxies for https://www.bse.cn

  --> Timer(Quick Verification (4.0s) for http://www.example.com, 10 in 4 passed) finished! Cost 4.0 Sec
  --> Timer(Final Verification (8.0s) for https://www.bse.cn, 4 in 4 passed) finished! Cost 5.8 Sec
  --> Timer(Load candidates, 10 loaded, 4 passed) finished! Cost 9.8 Sec
  --> Timer(Round 1 Find candidates, 205 found) finished! Cost 5.9 Sec
  --> Timer(Round 1 Quick Verification (4.0s) for http://www.example.com, 207 in 25 passed) finished! Cost 16.0 Sec
  --> Timer(Round 1 Final Verification (8.0s) for https://www.bse.cn, 25 in 3 passed) finished! Cost 8.0 Sec
  --> Timer(Round 2 Find candidates, 205 found) finished! Cost 5.7 Sec
  --> Timer(Round 2 Quick Verification (4.0s) for http://www.example.com, 199 in 27 passed) finished! Cost 16.0 Sec
  --> Timer(Round 2 Final Verification (8.0s) for https://www.bse.cn, 27 in 1 passed) finished! Cost 8.0 Sec
  --> Timer(Round 3 Find candidates, 205 found) finished! Cost 5.6 Sec
  --> Timer(Round 3 Quick Verification (4.0s) for http://www.example.com, 199 in 27 passed) finished! Cost 16.0 Sec
  --> Timer(Round 3 Final Verification (8.0s) for https://www.bse.cn, 27 in 1 passed) finished! Cost 8.0 Sec
************************************* Prepare Proxies Finish at 2026-03-24 15:30:05, Cost 4 Min 56 Sec *************************************

                               proxy_url  avg_time  max_time  90%_time
target_url             status
http://www.example.com False     1593       3.543     5.006     4.007
                       True       238       1.461     3.880     2.819
https://www.bse.cn     False       74       1.432     8.007     4.474
                       True         9       4.068     5.777     5.203
https://www.sse.com.cn False       81       2.060     8.007     8.002
                       True         9       3.818     7.778     7.117
https://www.szse.cn    False       58       1.377     8.005     3.875
                       True         7       3.877     6.198     5.412

In [29]:
pats = [r"可能.*(?:风险警示)",r"可能.*(?:退市)"]
cond = pd.concat([df["title"].str.contains(pat, regex=True, na=False) for pat in pats] , axis = 1).any(axis = 1)
df_new = df.loc[cond].loc[:,['sec_name','secid','title','date']].sort_values(by = 'secid')
df_new

      sec_name   secid                                        title      date
20514     深康佳Ａ      16               深康佳Ａ：关于公司股票交易可能被实施退市风险警示的提示性公告  20260131
30593     皇庭国际      56            皇庭国际：关于公司股票交易可能被实施退市风险警示的第二次提示性公告  20260228
21298     皇庭国际      56               皇庭国际：关于公司股票交易可能被实施退市风险警示的提示性公告  20260131
20052     ST中迪     609  ST中迪：中迪投资关于公司股票交易可能被叠加实施退市风险警示及其他风险警示的提示性公告  20260130
20795     西安旅游     610               西安旅游：关于公司股票交易可能被实施退市风险警示的提示性公告  20260131
...        ...     ...                                          ...       ...
2534      田野股份  920023     [临时公告]田野股份:内部控制整改进展暨股票可能被实施退市风险警示的风险提示公告  20260227
1201      田野股份  920023     [临时公告]田野股份:内部控制整改进展暨股票可能被实施退市风险警示的风险提示公告  20260130
2036      同辉信息  920090            [临时公告]同辉信息:关于股票可能被实施退市风险警示的风险提示公告  20260206
2652       数字人  920670      [临时公告]数字人:内部控制整改进展暨股票可能被实施退市风险警示的风险提示公告  20260227
1248       数字人  920670      [临时公告]数字人:内部控制整改进展暨股票可能被实施退市风险警示的风险提示公告  20260130

[92 rows x 4 columns]

In [25]:
df_new

NameError: name 'df_new' is not defined

In [ ]:
from src.data.crawler.announcement.agent import AnnouncementAgent
AnnouncementAgent.run_with_proxy(20260101,20260109,workers=6,go_with_cached_proxies=True)

Total Announcement Clawing Tasks: 27 at 20260101~20260109 for 3 exchanges
Timer(Warmup ProxyPool found proxies {'https://www.bse.cn': 7, 'https://www.sse.com.cn': 7, 'https://www.szse.cn': 7}) finished! Cost <1 Sec
  --> Execute with partitioning in Round 0, partition into 3 groups

26-03-27 12:34:51|HIGHLIGHT |: Get working proxies for https://www.bse.cn
26-03-27 12:34:51|HIGHLIGHT |: Get working proxies for https://www.sse.com.cn
26-03-27 12:34:51|HIGHLIGHT |: Get working proxies for https://www.szse.cn

  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260103.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260102.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260102.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260103.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260101.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260107.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260106.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260108.feather
Caution : requests.Session(timeout=(15.0, 150.0)) encountered TimeoutError (expand 2.0 times to retry): Failed to perform, curl: (28) Operation timed out after 165001 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Caution : requests.Session(timeout=(15.0, 150.0)) encountered TimeoutError (expand 2.0 times to retry): Failed to perform, curl: (28) Operation timed out after 165003 milliseconds with 15764 out of 43973 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260107.feather
    --> Finished executing 9 callers for group 0, 0 unfinished
    --> Try Refresh Proxy Pool for group 0 in round 0 finished
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260104.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260103.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260104.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260108.feather
Skipping: szse 20260105~20260105[http://103.84.95.54:7890] >> HTTP exception [curl_cffi.requests.exceptions.SSLError] will retry in 1.5s (1/2): Failed to perform, curl: (35) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260108.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260104.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260109.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260109.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260105.feather
    --> Finished executing 9 callers for group 1, 0 unfinished
    --> Try Refresh Proxy Pool for group 1 in round 0 finished
Skipping: szse 20260101~20260101[socks5://124.221.156.173:443] >> HTTP exception [curl_cffi.requests.exceptions.SSLError] will retry in 1.5s (1/2): Failed to perform, curl: (35) TLS connect error: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0). See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260109.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260101.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_bse/2026/announcement_bse.20260105.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260106.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260102.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260105.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_szse/2026/announcement_szse.20260107.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260106.feather
  -->  File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_crawler/announcement_sse/2026/announcement_sse.20260101.feather
    --> Finished executing 9 callers for group 2, 0 unfinished
    --> Try Refresh Proxy Pool for group 2 in round 0 finished

True

In [ ]:
from src.proj.util.proxy import ProxyAPI
# ProxyAPI.get_working_proxies('https://www.szse.cn' , timeout = 8)
ProxyAPI.verification_stats()

                               proxy_url  avg_time   max_time   90%_time
target_url             status
http://www.example.com False         175  3.877650   6.007287   5.013088
                       True           66  1.990516   4.968252   3.307946
https://www.bse.cn     False           4  2.528616   6.839466   5.450181
                       True            5  5.149178   9.009982   7.456175
https://www.sse.com.cn False           3  2.169151   4.190862   3.721936
                       True            6  3.504097   5.470520   5.291247
https://www.szse.cn    False          61  3.751688  10.008323  10.002091
                       True            3  2.469641   3.864118   3.573903

In [ ]:
from src.data.download.tushare.task.t00_info import Description
cal = Description()
cal.update_dates([20260321])

  --> description Overwritten : /Users/mengkjin/workspace/learndl/data/DataBase/DB_information_ts/description.feather

[20260321]

In [ ]:
from src.res.model.util.config import ModelConfig
from src.api import ModelAPI
import shutil
models = ModelAPI.available_models(True , True)
for model in models:
    config = ModelConfig(model , stage = 2 , resume = 1 , selection = 0)
    config.base_path.conf_file('algo').unlink(missing_ok = True)
    shutil.rmtree(config.base_path.conf('model') , ignore_errors = True)
    shutil.rmtree(config.base_path.conf('param') , ignore_errors = True)

In [ ]:
from src.res.model.util.config import ModelConfig
config = ModelConfig('st@nn@resnet_gru@gru_week')

In [ ]:
from src.res.model.model_module.application import ModelCalculator

calc = ModelCalculator('gru@gru_avg')
calc(20241213)

BatchData(input=BatchInput(x=tensor([[[-1.3656e-01, -3.4077e-02, -1.3469e-01, -1.2340e-01, -1.1457e-01,
          -3.7856e-01],
         [-1.5811e-01,  6.1276e-02, -4.6180e-02, -6.3696e-02, -2.3191e-02,
          -1.4315e-01],
         [-5.4606e-02,  9.3822e-03, -5.7149e-02, -1.8845e-02, -2.4513e-02,
          -2.4323e-01],
         ...,
         [ 9.9078e-03,  2.7259e-01,  5.0484e-02,  2.9587e-01,  2.0563e-01,
          -6.3920e-01],
         [-1.5036e-01,  7.1207e-01,  2.1807e-01,  4.0788e-01,  4.5367e-01,
          -7.1451e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
          -8.1852e-02]],

        [[ 4.2424e-01,  4.6481e-01,  4.1923e-01,  3.5978e-01,  3.7690e-01,
          -2.7611e-01],
         [ 3.3095e-01,  6.5460e-01,  5.9131e-01,  4.4826e-01,  5.8923e-01,
           1.2210e-02],
         [ 5.1696e-01,  7.7169e-01,  7.7667e-01,  5.2517e-01,  6.8634e-01,
           3.4659e-01],
         ...,
         [-1.8728e-01,  5.6482e-01,  3.9078e-01,  2.5427e-01,  4.8837e-01,
          -6.1944e-01],
         [ 1.5166e-01,  9.6239e-01,  4.5539e-01,  5.6701e-01,  7.7805e-01,
          -8.3579e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           1.5006e-01]],

        [[-6.7425e-01, -3.8722e-01, -3.9751e-01, -5.8505e-01, -5.3108e-01,
          -6.3285e-01],
         [-3.8021e-01, -1.5350e-01, -2.4756e-01, -3.2059e-01, -3.0909e-01,
          -6.1041e-01],
         [-1.7099e-01, -1.4584e-01, -1.7060e-01, -1.3792e-01, -1.7693e-01,
          -6.6493e-01],
         ...,
         [-2.0090e+00, -1.9770e+00, -2.8171e+00, -1.7509e+00, -2.3364e+00,
          -1.4803e+00],
         [-2.5919e+00, -8.3470e-02, -1.3355e+00, -2.2548e+00, -7.7943e-01,
          -1.3446e+00],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           2.4556e-01]],

        ...,

        [[-7.0246e-02, -7.3907e-02, -2.0177e-01, -1.2582e-01, -1.6253e-01,
          -2.4274e-01],
         [ 1.2013e-01,  1.9425e-01,  8.6393e-02,  1.6522e-01,  1.2121e-01,
           1.5860e-01],
         [ 3.8679e-01,  3.5638e-01,  3.7879e-01,  4.5978e-01,  3.5771e-01,
           3.5534e-01],
         ...,
         [ 4.0827e-01, -7.1407e-01, -4.5133e-01, -8.8651e-02, -6.6732e-01,
          -5.5132e-01],
         [-4.2685e-01, -7.1944e-01, -1.5969e+00, -5.9703e-01, -1.4120e+00,
          -8.1758e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           2.1827e-01]],

        [[-6.4627e-01, -7.5660e-01, -8.9494e-01, -5.8935e-01, -8.1059e-01,
          -5.7402e-01],
         [-2.4330e-01, -3.9898e-01, -5.2322e-01, -2.7105e-01, -4.5810e-01,
          -4.1798e-01],
         [ 1.4043e-01,  1.8365e-02, -5.5420e-02,  3.7968e-02, -5.0209e-02,
          -1.5029e-01],
         ...,
         [-4.3200e-01, -2.2617e+00, -2.4575e+00, -4.4776e-01, -1.9393e+00,
          -1.2188e+00],
         [-1.2522e+00, -2.5451e+00, -3.8033e+00, -1.8773e+00, -3.5722e+00,
          -1.3780e+00],
         [ 0.0000e+00,  0.0000e+00,  5.7215e-02,  0.0000e+00,  0.0000e+00,
           2.4556e-01]],

        [[-8.2435e-01, -5.9190e-01, -7.5081e-01, -8.7221e-01, -7.8233e-01,
           2.9619e-03],
         [-4.9025e-01, -2.9783e-01, -4.1982e-01, -4.5624e-01, -4.0655e-01,
           4.1860e-01],
         [ 2.1782e-01, -5.4877e-02, -5.2498e-02, -1.6716e-01, -6.9956e-02,
           1.2305e+00],
         ...,
         [ 1.1694e+00, -5.6889e-01, -6.9186e-02, -6.3055e-02, -2.1198e-01,
           4.6345e-02],
         [-1.6898e-01, -5.3050e-02, -1.2469e+00, -1.5797e+00, -1.6423e+00,
           2.5848e-01],
         [ 0.0000e+00, -5.7178e-02, -5.7215e-02,  0.0000e+00, -5.7179e-02,
           2.3191e-01]]], device='mps:0'), y=tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], device='mps:0'), w=None, i=tensor([[   0,   38],
        [   1,   38],
        [   2,   38],
        ...,
        [5542,   38],
        [5543,   38],
        [5544,   38]], device='mps:0'), valid=tensor([True, True, True,  ..., True, True, True], device='mps:0'), kwargs={}), output=BatchOutput(outputs=(tensor([[ 0.8483],
        [-0.2334],
        [-1.1192],
        ...,
        [-0.3721],
        [-0.2400],
        [-0.3133]], device='mps:0', grad_fn=<CatBackward0>), {'hidden': tensor([[-0.0709,  0.2944,  0.0050,  ..., -0.2303,  0.2847,  0.1345],
        [ 1.5227, -0.8635, -0.0444,  ...,  0.9613, -0.7736, -0.8312],
        [ 2.8161, -1.7795, -0.0923,  ...,  1.9938, -1.6412, -1.6858],
        ...,
        [ 1.7260, -1.0025, -0.0445,  ...,  1.1256, -0.9026, -0.9602],
        [ 1.5362, -0.8792, -0.0428,  ...,  0.9713, -0.7736, -0.8471],
        [ 1.6323, -0.9234, -0.0568,  ...,  1.0554, -0.8452, -0.9207]],
       device='mps:0', grad_fn=<LinearBackward0>)})))

In [ ]:
from src.res.model.util import PredictionModel
model = PredictionModel.SelectModels('gru_day_V1')[0]
model.load_pred(20241231)

       secid  gru_day_V1
0          1    1.126028
1          2    1.253377
2          4    0.986078
3          6    1.044249
4          7    0.795379
...      ...         ...
5176  920978    0.359580
5177  920981    2.206729
5178  920982    0.554663
5179  920985    1.038696
5180  920992    0.164047

[5181 rows x 2 columns]

In [ ]:
from src.res.factor.util.classes.universe import Universe
u = Universe('top-1000')
p = u.get(20241231,exclusions = 'loser')

In [ ]:
from src.data.update.custom.week_rank_loser import WeekRankLoserUpdater
WeekRankLoserUpdater.update_all('update')

    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100104.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100105.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100106.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100107.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100108.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100111.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100112.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100113.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100114.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100115.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100118.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100119.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100120.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100121.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100122.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100125.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100126.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100127.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100128.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100129.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100201.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100202.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100203.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100204.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100205.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100208.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100209.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100210.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100211.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100212.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100222.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100223.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100224.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100225.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100226.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100301.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100302.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100303.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100304.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100305.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100308.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100309.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100310.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100311.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100312.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100315.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100316.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100317.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100318.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100319.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100322.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100323.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100324.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100325.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100326.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100329.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100330.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100331.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100401.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100402.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100406.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100407.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100408.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100409.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100412.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100413.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100414.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100415.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100416.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100419.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100420.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100421.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100422.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100423.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100426.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100427.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100428.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100429.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100430.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100504.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100505.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100506.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100507.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100510.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100511.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100512.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100513.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100514.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100517.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100518.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100519.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100520.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100521.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100524.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100525.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100526.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100527.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100528.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100531.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100601.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100602.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100603.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100604.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100607.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100608.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100609.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100610.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100611.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100617.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100618.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100621.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100622.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100623.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100624.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100625.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100628.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100629.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100630.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100701.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100702.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100705.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100706.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100707.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100708.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100709.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100712.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100713.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100714.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100715.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100716.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100719.feather

In [ ]:
from src.proj import PATH
paths = []
for p in PATH.result.rglob('*.tar'):
    p.unlink()
    
for p in PATH.model.rglob('*.tar'):
    p.unlink()

paths

[PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest1/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest5/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest2/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest3/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest4/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/ht_master_combined.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/df_scores_v0.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/gru_day_V1.backtest/account.tar')]

In [ ]:
from datetime import datetime , time
from zoneinfo import ZoneInfo
beijing_tz = ZoneInfo("Asia/Shanghai")
datetime.now().astimezone().tzinfo , datetime.now(beijing_tz).astimezone().tzinfo

AttributeError: 'datetime.timezone' object has no attribute 'key'

In [ ]:
datetime.today() , datetime.now()

(datetime.datetime(2026, 3, 16, 9, 45, 20, 374246),
 datetime.datetime(2026, 3, 16, 9, 45, 20, 374307))

In [ ]:
datetime.now(beijing_tz)

datetime.datetime(2026, 3, 16, 21, 43, 27, 737842, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai'))

In [ ]:
from src.res.factor.util.classes.alpha_model import CompositeAlpha
alpha = CompositeAlpha(['sellside@huatai.master_combined@master_combined', 'factor@df_scores_v0', 'gru_day_V1'])
af = alpha.get(20241231)
af.item().to_dataframe()

       secid     alpha
0          1  1.483658
1          2  0.863664
2          4 -0.986211
3          6  0.542467
4          7 -0.121362
...      ...       ...
5224  920978 -0.164427
5225  920981  1.397860
5226  920982 -0.019465
5227  920985 -0.246272
5228  920992 -1.209771

[5229 rows x 2 columns]

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************