In [ ]:
"""
Function calls for the quick call buttons.
"""
from src.proj import Logger
from typing import Literal

class LoopFlag:
    def __init__(self , flag : Literal['go' , 'exit' , 'abort']):
        self.flag = flag

    @property
    def go(self) -> bool:
        return self.flag == 'go'
    @property
    def exit(self) -> bool:
        return self.flag == 'exit'
    @property
    def abort(self) -> bool:
        return self.flag == 'abort'

    def __bool__(self) -> bool:
        return self.go

def ask_for_selections(msg : str , options : int , start : int = 1) -> tuple[list[int] , LoopFlag]:
    """Parse the selections."""
    min , max = start , options + start - 1
    
    selection = input(f'{msg} ({min}-{max}, seperated by comma , q to quit): ')
    if selection.lower() == 'q':
        return [] , LoopFlag('exit')
    selections = [s.strip() for s in selection.split(',') if s.strip()]
    print(selections)
    if any(not s.isdigit() for s in selections):
        Logger.error(f'Contains non-digit characters: {selection}')
        return [] , LoopFlag('abort')

    selections = [int(i) for i in selections]
    if any(s < start or s > options + start - 1 for s in selections):
        Logger.error(f'Contains indices out of range [{min}-{max}]: {selection}')
        return [] , LoopFlag('abort')

    flag = input(f'Are you sure to resume the {len(selections)} selected models? (press y to confirm): ')
    if flag.lower() == 'y':
        return selections , LoopFlag('go')
    else:
        return [] , LoopFlag('abort')

ask_for_selections('abc' , 10)

['4', '']

26-06-03 11:41:50|ERROR     |: Contains non-digit characters: 4,

([], <__main__.LoopFlag at 0x103a454c0>)

In [1]:
from src.res.model.util import ModelPath
model_path = ModelPath('models/nn/gru@gru_global2top')

In [6]:
model_path.move_to_archive()

Success : models/nn/gru@gru_global2top has been moved to archive models/archive/nn@gru@gru_global2top.20260603102429

In [5]:
ModelPath.resume_from_archive('nn@gru@gru_global2top')

Success : models/archive/nn@gru@gru_global2top.20260603102312 has been reverted from archive models/nn/gru@gru_global2top

ModelPath(full_name=nn@gru@gru_global2top)

In [2]:
config.special

{'global2top': False, 'vae': False, 'tra': False, 'dsize': False}

In [31]:
import pandas as pd
pd.read_feather('models/st/boost@catboost@catboost_day/snapshot/basic_test/test_by_date.feather')

    model_num  model_date submodel      date     value
0           0    20241101     best  20241104  0.146341
1           0    20241101     best  20241105  0.034394
2           0    20241101     best  20241106  0.108401
3           0    20241101     best  20241107  0.016557
4           0    20241101     best  20241108 -0.003912
5           0    20241101     best  20241111  0.055963
6           0    20241101     best  20241112  0.010774
7           0    20241101     best  20241113 -0.045137
8           0    20241101     best  20241114  0.180610
9           0    20241101     best  20241115 -0.034938
10          0    20241101     best  20241118  0.173943
11          0    20241101     best  20241119  0.235771
12          0    20241101     best  20241120  0.131635
13          0    20241101     best  20241121  0.102724
14          0    20241101     best  20241122  0.151591
15          0    20241101     best  20241125  0.148694
16          0    20241101     best  20241126 -0.044280
17          0    20241101     best  20241127 -0.052741
18          0    20241101     best  20241128 -0.081117
19          0    20241101     best  20241129  0.068861
20          0    20241129     best  20241202  0.038803
21          0    20241129     best  20241203  0.065617
22          0    20241129     best  20241204 -0.040052
23          0    20241129     best  20241205  0.006865
24          0    20241129     best  20241206 -0.063520
25          0    20241129     best  20241209 -0.062166
26          0    20241129     best  20241210  0.166603
27          0    20241129     best  20241211  0.014428

In [32]:
import pandas as pd
pd.read_feather('models/st/boost@catboost@catboost_day/snapshot/basic_test/test_by_model.feather')

   model_num      stat submodel     value
0          0  20241101     best  0.065207
1          0  20241129     best  0.015822

In [1]:
import socket

def get_free_port(start_port=8080):
    """Finds an available TCP port starting from start_port."""
    port = start_port
    while True:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return port  # Port is free!
            except OSError:
                port += 1  # Occupied, try next port

get_free_port(6006)

6007

In [1]:
from collections import defaultdict
from datetime import datetime , timedelta
from src.proj import PATH , Logger

from src.proj.util import ScriptTool

In [ ]:
from src.proj.env.path import PATH
from src.proj.env.constant import Const
from src.proj.env.proj import Proj

In [2]:
import torch

step_len = 0
data_step = 1
d0 = 100
step_idx = torch.flip(100 - 1 - torch.arange(step_len) * data_step , [0])
date_idx = d0 + step_idx

In [8]:
import pandas as pd
pd.read_feather('models/nn/gru@gru_avg/snapshot/hidden_values/0.20241129.best.feather')

,secid,date,hidden.0,hidden.1,hidden.2,hidden.3,hidden.4,hidden.5,hidden.6,hidden.7,...,hidden.22,hidden.23,hidden.24,hidden.25,hidden.26,hidden.27,hidden.28,hidden.29,hidden.30,hidden.31
0,1,20230110,-0.440413,0.609544,0.022697,-0.461715,0.502916,0.134782,-0.404859,-0.361488,...,-0.716580,0.128878,0.242148,0.204995,-0.549165,-0.087166,-0.070447,-0.364030,0.504991,0.311549
1,2,20230110,0.192747,0.087388,-0.012713,0.076236,-0.090540,0.181036,0.017751,0.098645,...,-0.108836,-0.051339,-0.035171,-0.022317,-0.130715,-0.165364,0.061476,-0.045999,0.112595,-0.029328
2,4,20230110,1.418164,-0.795135,-0.051868,0.914632,-1.263076,0.509900,1.042001,1.065382,...,0.895278,-0.395818,-0.535441,-0.533388,0.836354,-0.551579,0.141262,0.868913,-0.727249,-0.782622
3,5,20230110,1.029563,-0.524697,-0.050824,0.663874,-0.910391,0.403831,0.708132,0.755309,...,0.593386,-0.287130,-0.392801,-0.364752,0.536816,-0.428198,0.115403,0.558255,-0.475538,-0.554758
4,6,20230110,3.426239,-2.184703,-0.134487,2.277928,-3.031193,1.016665,2.754787,2.738304,...,2.464027,-1.004132,-1.353453,-1.531356,2.449146,-1.157178,0.297285,2.454199,-2.094682,-2.109489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492816,920679,20241211,2.175831,-1.301828,-0.085192,1.413940,-1.926255,0.722641,1.683338,1.680319,...,1.478877,-0.627968,-0.845888,-0.893586,1.449613,-0.794840,0.178808,1.455910,-1.247711,-1.284076
492817,920693,20241211,2.398903,-1.461589,-0.086054,1.567075,-2.128423,0.770638,1.857238,1.871693,...,1.663926,-0.684689,-0.932756,-1.016790,1.652217,-0.858269,0.212158,1.635984,-1.412724,-1.437031
492818,920703,20241211,2.114833,-1.276595,-0.070441,1.387199,-1.875636,0.689219,1.637330,1.638620,...,1.434775,-0.599495,-0.815014,-0.879472,1.394777,-0.767889,0.193370,1.416089,-1.197999,-1.233804
492819,920026,20241211,3.885445,-2.477729,-0.143345,2.557758,-3.438684,1.157270,3.133110,3.097316,...,2.813776,-1.140416,-1.534752,-1.731706,2.820187,-1.301664,0.318412,2.799323,-2.420780,-2.411430
492820,920833,20241211,1.537444,-0.853001,-0.061853,0.975697,-1.374669,0.563404,1.151444,1.159036,...,0.992480,-0.455044,-0.591057,-0.574605,0.917434,-0.593579,0.138495,0.961046,-0.807841,-0.871313

In [1]:
from src.proj.util.emailer import get_email_setting
get_email_setting('sender')

'mengkjin@163.com'

In [1]:
from src.res.model.model_module.application import ArchivedPredictorModel 
from src.res.model.util import PredictorPath
path = PredictorPath.SelectModels('gru_day_V0')[0]
model = ArchivedPredictorModel(path)

In [2]:
path.pred_target_dates , path.pred_dates

(array([20170104, 20170105, 20170106, ..., 20250416, 20250417, 20250418]),
 array([20170104, 20170105, 20170106, ..., 20241227, 20241230, 20241231]))

In [ ]:
block = model.hidden_block(20170101 , 20170105 , 20170103 , silent = False)

    --> Timer(query y block) finished! Cost 0.0000 Sec
    --> Timer(get ext dates for y block) finished! Cost 0.0002 Sec
    --> Timer(load ext y block of length 4361) finished! Cost 0.0756 Sec
    --> Timer(merge y ext block) finished! Cost 0.0000 Sec
    --> Timer(append y block to cache) finished! Cost 0.0000 Sec
    --> Timer(query day block) finished! Cost 0.0000 Sec
    --> Timer(get ext dates for day block) finished! Cost 0.0001 Sec
    --> Timer(load ext day block of length 4361) finished! Cost 0.0792 Sec
    --> Timer(merge day ext block) finished! Cost 0.0000 Sec
    --> Timer(append day block to cache) finished! Cost 0.0000 Sec
  --> Timer(Load DataBlock [y,day] at 20070101~20241211) finished! Cost 0.1554 Sec
align y block , inplace = True
align day block , inplace = True
  --> Timer(Align DataBlock [y,day]) finished! Cost 0.0878 Sec

In [2]:
from src.res.factor.calculator.updater import StockFactorUpdater
from cProfile import Profile
updater = StockFactorUpdater()
with Profile() as pr:
    updater.collect_jobs()
pr.print_stats('cumtime')

  --> StockFactorUpdater >> Success : Collecting 370 Jobs for StockFactorUpdater
         18485050 function calls (17522027 primitive calls) in 7.296 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      452    0.002    0.000   29.137    0.064 _base.py:428(result)
  904/864    0.004    0.000   23.069    0.027 factor_calc.py:27(_slice_dates)
  904/864    0.029    0.000   22.543    0.026 cal.py:428(slice)
13556/6789    0.089    0.000   16.487    0.002 pathlib.py:1059(_scandir)
  904/845    0.003    0.000   14.851    0.018 arraysetops.py:138(unique)
  452/400    0.004    0.000    9.003    0.023 cal.py:342(diffs)
  435/428    0.026    0.000    7.457    0.017 {method 'argsort' of 'numpy.ndarray' objects}
      2/1    0.001    0.001    7.295    7.295 updater.py:67(collect_jobs)
        1    0.000    0.000    7.248    7.248 parallel.py:48(parallel)
        1    0.000    0.000    7.248    7.248 _base.py:646(__exit__)
        1    0.000    0.000    7.248    7.248 thread.py:220(shutdown)
        8    0.000    0.000    7.248    0.906 threading.py:1117(join)
       12    0.000    0.000    7.248    0.604 threading.py:1155(_wait_for_tstate_lock)
      8/1    0.000    0.000    7.247    7.247 threading.py:1018(_bootstrap)
      8/1    0.000    0.000    7.247    7.247 threading.py:1058(_bootstrap_inner)
      8/1    0.000    0.000    7.247    7.247 ipkernel.py:750(run_closure)
      8/1    0.000    0.000    7.247    7.247 threading.py:1001(run)
      8/1    0.000    0.000    7.247    7.247 thread.py:70(_worker)
      8/1    0.000    0.000    7.247    7.247 {method 'get' of '_queue.SimpleQueue' objects}
    453/2    0.094    0.000    7.247    3.624 db_path.py:21(file_dates)
    452/1    0.004    0.000    7.246    7.246 thread.py:54(run)
    452/1    0.004    0.000    7.246    7.246 parallel.py:169(go)
    452/1    0.007    0.000    7.246    7.246 parallel.py:147(try_call)
    452/1    0.003    0.000    7.246    7.246 factor_calc.py:443(target_dates)
    452/1    0.006    0.000    7.246    7.246 factor_calc.py:435(missing_dates)
    452/1    0.004    0.000    7.246    7.246 factor_calc.py:448(stored_dates)
    452/1    0.006    0.000    7.246    7.246 db_path.py:295(dates)
    452/1    0.027    0.000    7.246    7.246 db_path.py:143(dates)
    452/1    0.063    0.000    7.246    7.246 db_path.py:31(dir_dates)
 302959/1    0.077    0.000    7.241    7.241 pathlib.py:1097(rglob)
907760/903584    0.127    0.000    1.919    0.000 pathlib.py:583(name)
1223521/1218617    0.199    0.000    1.789    0.000 pathlib.py:569(_tail)
303031/301637    0.126    0.000    1.579    0.000 pathlib.py:407(_load_parts)
303483/302087    0.839    0.000    1.418    0.000 pathlib.py:387(_parse_path)
13556/6789    0.763    0.000    1.142    0.000 {built-in method posix.scandir}
   315307    0.291    0.000    0.973    0.000 pathlib.py:1065(_make_child_relpath)
  452/401    0.006    0.000    0.965    0.002 arraysetops.py:939(setdiff1d)
1357/1296    0.055    0.000    0.858    0.001 {method 'sort' of 'numpy.ndarray' objects}
618793/618792    0.196    0.000    0.798    0.000 pathlib.py:1157(__init__)
618793/618792    0.430    0.000    0.602    0.000 pathlib.py:358(__init__)
   316216    0.131    0.000    0.601    0.000 pathlib.py:380(with_segments)
  3023519    0.355    0.000    0.355    0.000 {built-in method sys.intern}
  904/845    0.036    0.000    0.290    0.000 arraysetops.py:323(_unique1d)
   302606    0.114    0.000    0.227    0.000 pathlib.py:618(stem)
   618793    0.113    0.000    0.182    0.000 pathlib.py:1164(__new__)
  452/429    0.036    0.000    0.166    0.000 arraysetops.py:524(in1d)
   303483    0.102    0.000    0.147    0.000 <frozen posixpath>:138(splitroot)
1808/1777    0.026    0.000    0.142    0.000 {method 'astype' of 'numpy.ndarray' objects}
  452/416    0.044    0.000    0.139    0.000 factor_calc.py:119(__get__)
  904/894    0.002    0.000    0.131    0.000 cal.py:40(get_cds)
1302904/1301088    0.101    0.000    0.104    0.000 {built-in method builtins.isinstance}
   303484    0.076    0.000    0.076    0.000 {method 'split' of 'str' objects}
   620508    0.071    0.000    0.071    0.000 {method 'append' of 'list' objects}
   618881    0.069    0.000    0.069    0.000 {built-in method __new__ of type object at 0x10475ca30}
1210853/1210851    0.068    0.000    0.068    0.000 {built-in method builtins.len}
   302532    0.067    0.000    0.067    0.000 {method 'match' of 're.Pattern' objects}
  904/895    0.008    0.000    0.043    0.000 {method 'flatten' of 'numpy.ndarray' objects}
   302606    0.041    0.000    0.041    0.000 {method 'rfind' of 'str' objects}
   304883    0.041    0.000    0.041    0.000 {method 'startswith' of 'str' objects}
   620216    0.041    0.000    0.041    0.000 {built-in method posix.fspath}
   304735    0.040    0.000    0.040    0.000 {method 'endswith' of 'str' objects}
  452/446    0.001    0.000    0.039    0.000 pathlib.py:164(select_from)
   303489    0.037    0.000    0.037    0.000 {method 'extend' of 'list' objects}
   302507    0.037    0.000    0.037    0.000 {method 'is_dir' of 'posix.DirEntry' objects}
   605014    0.034    0.000    0.034    0.000 pathlib.py:176(_select_from)
        1    0.000    0.000    0.031    0.031 module.py:145(success)
        1    0.000    0.000    0.031    0.031 logger.py:257(success)
        1    0.000    0.000    0.031    0.031 logger.py:65(new_stdout)
        1    0.000    0.000    0.031    0.031 logger.py:61(add_to_log_file)
  481/475    0.001    0.000    0.031    0.000 pathlib.py:870(is_dir)
   315761    0.025    0.000    0.030    0.000 pathlib.py:551(drive)
        1    0.000    0.000    0.030    0.030 logger.py:51(find_calling_module)
        1    0.000    0.000    0.030    0.030 inspect.py:1779(stack)
        1    0.000    0.000    0.030    0.030 inspect.py:1749(getouterframes)
       29    0.000    0.000    0.030    0.001 inspect.py:1688(getframeinfo)
   329377    0.023    0.000    0.030    0.000 pathlib.py:437(__str__)
       38    0.013    0.000    0.029    0.001 inspect.py:988(getmodule)
   302577    0.028    0.000    0.028    0.000 {method 'isdigit' of 'str' objects}
  7220/71    0.749    0.000    0.026    0.000 pathlib.py:1112(walk)
  482/476    0.001    0.000    0.023    0.000 pathlib.py:835(stat)
1357/1356    0.022    0.000    0.022    0.000 {built-in method numpy.array}
       29    0.000    0.000    0.022    0.001 inspect.py:1070(findsource)
  513/507    0.011    0.000    0.020    0.000 {built-in method posix.stat}
   315761    0.020    0.000    0.020    0.000 pathlib.py:560(root)
1768/1760    0.003    0.000    0.017    0.000 fromnumeric.py:71(_wrapreduction)
     2126    0.009    0.000    0.016    0.000 ipkernel.py:781(_clean_thread_parent_frames)
       64    0.000    0.000    0.014    0.000 inspect.py:951(getsourcefile)
    14070    0.005    0.000    0.013    0.000 pathlib.py:447(__fspath__)
309285/1916    0.831    0.000    0.013    0.000 pathlib.py:200(_select_from)
  884/882    0.001    0.000    0.010    0.000 fromnumeric.py:2692(max)
  884/882    0.001    0.000    0.010    0.000 fromnumeric.py:2836(min)
      452    0.000    0.000    0.010    0.000 parallel.py:173(submit)
      452    0.001    0.000    0.009    0.000 thread.py:165(submit)
      2/1    0.000    0.000    0.009    0.009 cal.py:179(updated)
        1    0.000    0.000    0.009    0.009 db_path.py:320(max_date)
        1    0.000    0.000    0.009    0.009 db_path.py:168(max_date)
1768/1760    0.008    0.000    0.009    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.000    0.000    0.008    0.008 db_path.py:138(years)
      159    0.000    0.000    0.007    0.000 pathlib.py:1050(iterdir)
     3677    0.002    0.000    0.006    0.000 {built-in method builtins.getattr}
      158    0.000    0.000    0.006    0.000 {built-in method builtins.any}
  452/451    0.001    0.000    0.006    0.000 cal.py:540(__new__)
      452    0.000    0.000    0.006    0.000 thread.py:184(_adjust_thread_count)
    44525    0.006    0.000    0.006    0.000 {built-in method builtins.hasattr}
      454    0.000    0.000    0.006    0.000 db_path.py:106(parent)
       31    0.006    0.000    0.006    0.000 {built-in method posix.listdir}
    43205    0.004    0.000    0.006    0.000 inspect.py:298(ismodule)
      454    0.001    0.000    0.005    0.000 db_path.py:81(Parent)
        1    0.000    0.000    0.005    0.005 updater.py:53(calculators)
      453    0.001    0.000    0.005    0.000 factor_calc.py:581(iter)
      915    0.001    0.000    0.004    0.000 factor_calc.py:93(__get__)
      909    0.001    0.000    0.004    0.000 pathlib.py:711(joinpath)
      452    0.001    0.000    0.004    0.000 threading.py:468(acquire)
      452    0.001    0.000    0.004    0.000 _base.py:537(set_result)
      463    0.001    0.000    0.004    0.000 factor_calc.py:608(match_attrs)
    42434    0.004    0.000    0.004    0.000 {method 'get' of 'dict' objects}
      452    0.000    0.000    0.003    0.000 factor_calc.py:98(__get__)
      908    0.001    0.000    0.003    0.000 typing.py:1221(__instancecheck__)
 7220/219    0.123    0.000    0.003    0.000 pathlib.py:228(_iterate_directories)
     1063    0.002    0.000    0.003    0.000 threading.py:1535(enumerate)
      452    0.001    0.000    0.003    0.000 parallel.py:121(unwrap)
    13556    0.003    0.000    0.003    0.000 {method '__exit__' of 'posix.ScandirIterator' objects}
     1834    0.002    0.000    0.002    0.000 threading.py:299(__enter__)
      908    0.001    0.000    0.002    0.000 typing.py:1492(__subclasscheck__)
      471    0.002    0.000    0.002    0.000 <frozen posixpath>:71(join)
    16997    0.002    0.000    0.002    0.000 threading.py:1198(ident)
      905    0.001    0.000    0.002    0.000 machine.py:298(preference)
      452    0.000    0.000    0.002    0.000 factor.py:22(start)
        1    0.000    0.000    0.002    0.002 decorator.py:232(fun)
      460    0.000    0.000    0.002    0.000 threading.py:424(notify_all)
     2107    0.001    0.000    0.002    0.000 factor_calc.py:51(__get__)
     1821    0.001    0.000    0.002    0.000 singleton.py:11(get_instance)
     1326    0.002    0.000    0.002    0.000 getlimits.py:685(__init__)
      905    0.001    0.000    0.002    0.000 factor.py:310(UPDATE)
      908    0.001    0.000    0.001    0.000 {built-in method builtins.issubclass}
     6778    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}
      452    0.000    0.000    0.001    0.000 _base.py:328(__init__)
        8    0.000    0.000    0.001    0.000 threading.py:975(start)
      468    0.001    0.000    0.001    0.000 threading.py:394(notify)
      461    0.001    0.000    0.001    0.000 threading.py:277(__init__)
      905    0.001    0.000    0.001    0.000 machine.py:170(get)
        1    0.000    0.000    0.001    0.001 history.py:92(only_when_enabled)
      915    0.000    0.000    0.001    0.000 factor.py:340(STOCK)
     1346    0.001    0.000    0.001    0.000 {built-in method numpy.empty}
     1357    0.001    0.000    0.001    0.000 {built-in method builtins.all}
      452    0.000    0.000    0.001    0.000 {method 'view' of 'numpy.ndarray' objects}
      452    0.000    0.000    0.001    0.000 _base.py:497(set_running_or_notify_cancel)
      908    0.000    0.000    0.001    0.000 <frozen abc>:121(__subclasscheck__)
     1834    0.001    0.000    0.001    0.000 threading.py:302(__exit__)
      453    0.000    0.000    0.001    0.000 factor.py:26(end)
      915    0.001    0.000    0.001    0.000 factor.py:231(cat0_to_meta)
     2107    0.001    0.000    0.001    0.000 factor_calc.py:41(__get__)
        5    0.000    0.000    0.001    0.000 events.py:86(_run)
        5    0.000    0.000    0.001    0.000 {method 'run' of '_contextvars.Context' objects}
      452    0.000    0.000    0.001    0.000 factor_calc.py:109(__get__)
        4    0.000    0.000    0.001    0.000 base_events.py:1922(_run_once)
     4252    0.001    0.000    0.001    0.000 {method 'keys' of 'dict' objects}
      908    0.001    0.000    0.001    0.000 {built-in method _abc._abc_subclasscheck}
      904    0.000    0.000    0.001    0.000 cal.py:285(as_end_date)
        3    0.000    0.000    0.001    0.000 zmqstream.py:573(_handle_events)
      789    0.001    0.000    0.001    0.000 {method 'release' of '_thread.lock' objects}
     3678    0.001    0.000    0.001    0.000 {method '__exit__' of '_thread.lock' objects}
     2707    0.001    0.000    0.001    0.000 {method 'items' of 'dict' objects}
       29    0.000    0.000    0.001    0.000 inspect.py:1681(_get_code_position)
        2    0.000    0.000    0.001    0.000 asyncio.py:206(_handle_events)
     1356    0.001    0.000    0.001    0.000 {method '__enter__' of '_thread.RLock' objects}
      452    0.000    0.000    0.000    0.000 cal.py:568(__array_finalize__)
       37    0.000    0.000    0.000    0.000 {built-in method builtins.next}
      453    0.000    0.000    0.000    0.000 db_path.py:53(__new__)
 302949/1    0.146    0.000    0.000    0.000 pathlib.py:234(_select_from)
      904    0.000    0.000    0.000    0.000 arraysetops.py:125(_unpack_tuple)
     2444    0.000    0.000    0.000    0.000 {method '__exit__' of '_thread.RLock' objects}
      452    0.000    0.000    0.000    0.000 singleton.py:32(__call__)
      370    0.000    0.000    0.000    0.000 update_jobs.py:319(__init__)
     2126    0.000    0.000    0.000    0.000 {method 'values' of 'dict' objects}
      454    0.000    0.000    0.000    0.000 pathlib.py:429(_format_parsed_parts)
      904    0.000    0.000    0.000    0.000 {method 'ravel' of 'numpy.ndarray' objects}
      783    0.000    0.000    0.000    0.000 {built-in method _thread.allocate_lock}
      934    0.000    0.000    0.000    0.000 {built-in method builtins.max}
     1356    0.000    0.000    0.000    0.000 arraysetops.py:630(<genexpr>)
        3    0.000    0.000    0.000    0.000 zmqstream.py:614(_handle_recv)
        1    0.000    0.000    0.000    0.000 parallel.py:177(from_func_calls)
      905    0.000    0.000    0.000    0.000 machine.py:196(_get_content)
        3    0.000    0.000    0.000    0.000 zmqstream.py:546(_run_callback)
        8    0.000    0.000    0.000    0.000 {method 'copy' of 'dict' objects}
     1808    0.000    0.000    0.000    0.000 {built-in method numpy.asanyarray}
      370    0.000    0.000    0.000    0.000 update_jobs.py:46(__init__)
        4    0.000    0.000    0.000    0.000 selectors.py:558(select)
      312    0.000    0.000    0.000    0.000 {method '_acquire_restore' of '_thread.RLock' objects}
      460    0.000    0.000    0.000    0.000 {method 'get_nowait' of '_queue.SimpleQueue' objects}
      452    0.000    0.000    0.000    0.000 cal.py:30(get_cd)
        8    0.000    0.000    0.000    0.000 {built-in method _thread.start_new_thread}
      884    0.000    0.000    0.000    0.000 getlimits.py:709(max)
        1    0.000    0.000    0.000    0.000 logfile.py:212(write)
      476    0.000    0.000    0.000    0.000 {built-in method builtins.min}
     1356    0.000    0.000    0.000    0.000 {built-in method numpy.asarray}
       14    0.000    0.000    0.000    0.000 inspect.py:976(getabsfile)
        8    0.000    0.000    0.000    0.000 ipkernel.py:774(init_closure)
      477    0.000    0.000    0.000    0.000 threading.py:314(_is_owned)
        3    0.000    0.000    0.000    0.000 iostream.py:157(_handle_event)
        8    0.000    0.000    0.000    0.000 threading.py:884(__init__)
        1    0.000    0.000    0.000    0.000 logfile.py:184(write_entry)
      915    0.000    0.000    0.000    0.000 factor.py:205(category0)
       68    0.000    0.000    0.000    0.000 package_importer.py:721(_patched_getfile)
      772    0.000    0.000    0.000    0.000 {method 'remove' of 'collections.deque' objects}
       15    0.000    0.000    0.000    0.000 <frozen posixpath>:408(abspath)
        1    0.000    0.000    0.000    0.000 update_jobs.py:223(sort_jobs)
        1    0.000    0.000    0.000    0.000 {method 'sort' of 'list' objects}
      904    0.000    0.000    0.000    0.000 cal.py:277(as_start_date)
        6    0.000    0.000    0.000    0.000 attrsettr.py:43(__getattr__)
        4    0.000    0.000    0.000    0.000 {method 'control' of 'select.kqueue' objects}
      460    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        1    0.000    0.000    0.000    0.000 history.py:1024(writeout_cache)
      442    0.000    0.000    0.000    0.000 getlimits.py:696(min)
       68    0.000    0.000    0.000    0.000 inspect.py:911(getfile)
      461    0.000    0.000    0.000    0.000 threading.py:308(_release_save)
      371    0.000    0.000    0.000    0.000 module.py:281(vb_level)
      487    0.000    0.000    0.000    0.000 <frozen posixpath>:41(_get_sep)
       27    0.000    0.000    0.000    0.000 linecache.py:52(checkcache)
        2    0.000    0.000    0.000    0.000 iostream.py:276(<lambda>)
      461    0.000    0.000    0.000    0.000 threading.py:311(_acquire_restore)
      452    0.000    0.000    0.000    0.000 threading.py:124(RLock)
        6    0.000    0.000    0.000    0.000 {built-in method posix.getcwd}
        6    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
        2    0.000    0.000    0.000    0.000 iostream.py:278(_really_send)
      779    0.000    0.000    0.000    0.000 {method 'append' of 'collections.deque' objects}
      926    0.000    0.000    0.000    0.000 {method 'replace' of 'str' objects}
      914    0.000    0.000    0.000    0.000 {built-in method time.monotonic}
        2    0.000    0.000    0.000    0.000 socket.py:700(send_multipart)
      894    0.000    0.000    0.000    0.000 {built-in method sys.audit}
        1    0.000    0.000    0.000    0.000 output.py:132(stdout)
        3    0.000    0.000    0.000    0.000 zmqstream.py:653(_rebuild_io_state)
        8    0.000    0.000    0.000    0.000 threading.py:588(__init__)
      312    0.000    0.000    0.000    0.000 {method '_release_save' of '_thread.RLock' objects}
       15    0.000    0.000    0.000    0.000 socket.py:623(send)
        1    0.000    0.000    0.000    0.000 output.py:116(write)
      453    0.000    0.000    0.000    0.000 db_path.py:58(__init__)
      904    0.000    0.000    0.000    0.000 arraysetops.py:133(_unique_dispatcher)
      478    0.000    0.000    0.000    0.000 {method '__enter__' of '_thread.lock' objects}
      764    0.000    0.000    0.000    0.000 {method '_is_owned' of '_thread.RLock' objects}
        1    0.000    0.000    0.000    0.000 ioloop.py:750(_run_callback)
        1    0.000    0.000    0.000    0.000 zmqstream.py:684(<lambda>)
        3    0.000    0.000    0.000    0.000 zmqstream.py:676(_update_handler)
        1    0.000    0.000    0.000    0.000 interactiveshell.py:3043(write)
      870    0.000    0.000    0.000    0.000 multiarray.py:153(concatenate)
        1    0.000    0.000    0.000    0.000 {method '__exit__' of '_io._IOBase' objects}
      884    0.000    0.000    0.000    0.000 fromnumeric.py:2831(_min_dispatcher)
        1    0.000    0.000    0.000    0.000 history.py:1008(_writeout_input_cache)
        2    0.000    0.000    0.000    0.000 {method '__exit__' of 'sqlite3.Connection' objects}
      884    0.000    0.000    0.000    0.000 fromnumeric.py:2687(_max_dispatcher)
      370    0.000    0.000    0.000    0.000 update_jobs.py:224(<lambda>)
      452    0.000    0.000    0.000    0.000 _base.py:337(_invoke_callbacks)
      452    0.000    0.000    0.000    0.000 parallel.py:104(__init__)
        1    0.000    0.000    0.000    0.000 cProfile.py:119(__exit__)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 iostream.py:655(write)

In [2]:
from src.res.factor.calculator.updater import FactorStatsUpdater
from cProfile import Profile
updater = FactorStatsUpdater()
with Profile() as pr:
    updater.collect_jobs()
pr.print_stats('cumtime')

  --> FactorStatsUpdater >> Success : Collecting 12280 Jobs for FactorStatsUpdater
         26172337 function calls (25385754 primitive calls) in 22.266 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      459    0.002    0.000  110.692    0.241 _base.py:428(result)
        8    0.000    0.000   66.273    8.284 threading.py:1117(join)
       15    0.000    0.000   66.273    4.418 threading.py:1155(_wait_for_tstate_lock)
  462/198    0.012    0.000   29.927    0.151 db_path.py:295(dates)
  453/199    0.006    0.000   29.272    0.147 factor_calc.py:448(stored_dates)
  462/198    0.010    0.000   26.506    0.134 db_path.py:143(dates)
        1    0.010    0.010   22.241   22.241 updater.py:67(collect_jobs)
    919/2    0.009    0.000   22.123   11.062 cal.py:179(updated)
    919/2    0.014    0.000   22.123   11.061 db_path.py:320(max_date)
    919/2    0.045    0.000   22.123   11.061 db_path.py:168(max_date)
    919/2    0.049    0.000   22.120   11.060 db_path.py:138(years)
30456/190    0.026    0.000   22.106    0.116 {built-in method builtins.any}
146121/300    0.148    0.000   22.099    0.074 pathlib.py:1050(iterdir)
        1    0.000    0.000   22.092   22.092 parallel.py:48(parallel)
        1    0.000    0.000   22.091   22.091 _base.py:646(__exit__)
        1    0.000    0.000   22.091   22.091 thread.py:220(shutdown)
      8/1    0.000    0.000   22.091   22.091 threading.py:1018(_bootstrap)
      8/1    0.000    0.000   22.091   22.091 threading.py:1058(_bootstrap_inner)
      8/1    0.000    0.000   22.091   22.091 ipkernel.py:750(run_closure)
      8/1    0.000    0.000   22.091   22.091 threading.py:1001(run)
      8/1    0.000    0.000   22.091   22.091 thread.py:70(_worker)
      8/1    0.000    0.000   22.091   22.091 {method 'get' of '_queue.SimpleQueue' objects}
    459/1    0.003    0.000   22.090   22.090 thread.py:54(run)
    459/1    0.004    0.000   22.090   22.090 parallel.py:169(go)
    459/1    0.009    0.000   22.090   22.090 parallel.py:147(try_call)
    459/1    0.048    0.000   22.090   22.090 factor_calc.py:563(stats_target_dates)
320228/120779    0.073    0.000    4.819    0.000 pathlib.py:1097(rglob)
 1381/555    0.273    0.000    2.993    0.005 db_path.py:21(file_dates)
  462/198    0.059    0.000    2.931    0.015 db_path.py:31(dir_dates)
320215/120918    0.252    0.000    2.739    0.000 pathlib.py:234(_select_from)
27113/25274    0.025    0.000    2.378    0.000 pathlib.py:870(is_dir)
326630/191543    2.337    0.000    2.376    0.000 pathlib.py:200(_select_from)
1178939/1178935    0.160    0.000    2.076    0.000 pathlib.py:583(name)
1633303/1633047    0.247    0.000    1.944    0.000 pathlib.py:569(_tail)
7313/5280    2.226    0.000    1.917    0.000 pathlib.py:1112(walk)
29868/27778    0.021    0.000    1.803    0.000 pathlib.py:835(stat)
   388232    0.160    0.000    1.747    0.000 pathlib.py:407(_load_parts)
   388694    0.802    0.000    1.527    0.000 pathlib.py:387(_parse_path)
   450228    0.420    0.000    1.401    0.000 pathlib.py:1065(_make_child_relpath)
13728/12882    0.012    0.000    1.220    0.000 pathlib.py:1059(_scandir)
13728/12882    0.932    0.000    1.077    0.000 {built-in method posix.scandir}
29899/27809    0.861    0.000    1.037    0.000 {built-in method posix.stat}
  459/457    0.003    0.000    1.022    0.002 factor_calc.py:550(stats_stored_dates)
842597/842243    0.268    0.000    0.897    0.000 pathlib.py:1157(__init__)
   457583    0.210    0.000    0.891    0.000 pathlib.py:380(with_segments)
  918/913    0.006    0.000    0.877    0.001 df_io.py:364(load)
  918/910    0.023    0.000    0.803    0.001 arraysetops.py:939(setdiff1d)
842597/842243    0.410    0.000    0.633    0.000 pathlib.py:358(__init__)
2763/2748    0.008    0.000    0.514    0.000 arraysetops.py:138(unique)
      465    0.001    0.000    0.499    0.001 factor_calc.py:27(_slice_dates)
  3869014    0.443    0.000    0.443    0.000 {built-in method sys.intern}
   410747    0.156    0.000    0.311    0.000 pathlib.py:618(stem)
      465    0.040    0.000    0.308    0.001 cal.py:428(slice)
7313/5288    0.004    0.000    0.296    0.000 pathlib.py:228(_iterate_directories)
   842597    0.146    0.000    0.240    0.000 pathlib.py:1164(__new__)
        9    0.000    0.000    0.235    0.026 arraysetops.py:898(union1d)
4144/4133    0.091    0.000    0.225    0.000 {method 'sort' of 'numpy.ndarray' objects}
  918/915    0.002    0.000    0.221    0.000 df_io.py:212(load_df)
  918/915    0.003    0.000    0.203    0.000 df_io.py:35(load_pandas)
   618724    0.133    0.000    0.193    0.000 trade_date.py:66(__ge__)
   388694    0.127    0.000    0.181    0.000 <frozen posixpath>:138(splitroot)
1882047/1875603    0.152    0.000    0.165    0.000 {built-in method builtins.isinstance}
      916    0.007    0.000    0.165    0.000 frame.py:694(__init__)
2763/2748    0.076    0.000    0.146    0.000 arraysetops.py:323(_unique1d)
      916    0.006    0.000    0.132    0.000 construction.py:423(dict_to_mgr)
  918/917    0.001    0.000    0.105    0.000 db_path.py:228(path)
   522316    0.041    0.000    0.098    0.000 pathlib.py:437(__str__)
   391451    0.098    0.000    0.098    0.000 {method 'split' of 'str' objects}
2755/2743    0.003    0.000    0.096    0.000 pathlib.py:852(exists)
   846413    0.094    0.000    0.094    0.000 {built-in method __new__ of type object at 0x1021c8a30}
1589016/1572444    0.090    0.000    0.092    0.000 {built-in method builtins.len}
    72088    0.021    0.000    0.090    0.000 pathlib.py:447(__fspath__)
2748/1832    0.014    0.000    0.088    0.000 series.py:389(__init__)
   791081    0.087    0.000    0.087    0.000 {method 'append' of 'list' objects}
   454364    0.033    0.000    0.083    0.000 pathlib.py:551(drive)
   319803    0.068    0.000    0.068    0.000 {method 'match' of 're.Pattern' objects}
   620560    0.061    0.000    0.061    0.000 trade_date.py:42(__int__)
   410747    0.058    0.000    0.058    0.000 {method 'rfind' of 'str' objects}
   402078    0.053    0.000    0.053    0.000 {method 'startswith' of 'str' objects}
   401906    0.052    0.000    0.052    0.000 {method 'endswith' of 'str' objects}
   850480    0.051    0.000    0.051    0.000 {built-in method posix.fspath}
    12280    0.037    0.000    0.049    0.000 update_jobs.py:390(__init__)
      916    0.000    0.000    0.045    0.000 series.py:5784(isna)
      916    0.001    0.000    0.044    0.000 generic.py:8712(isna)
      916    0.002    0.000    0.040    0.000 series.py:607(_init_dict)
   392376    0.039    0.000    0.039    0.000 {method 'extend' of 'list' objects}
      920    0.000    0.000    0.039    0.000 missing.py:101(isna)
      920    0.003    0.000    0.039    0.000 missing.py:184(_isna)
   319766    0.037    0.000    0.037    0.000 {method 'is_dir' of 'posix.DirEntry' objects}
   639532    0.036    0.000    0.036    0.000 pathlib.py:176(_select_from)
        1    0.000    0.000    0.033    0.033 module.py:145(success)
        1    0.000    0.000    0.033    0.033 logger.py:257(success)
        1    0.000    0.000    0.033    0.033 logger.py:65(new_stdout)
        1    0.000    0.000    0.033    0.033 logger.py:61(add_to_log_file)
        1    0.000    0.000    0.033    0.033 logger.py:51(find_calling_module)
        1    0.000    0.000    0.033    0.033 inspect.py:1779(stack)
        1    0.000    0.000    0.033    0.033 inspect.py:1749(getouterframes)
       29    0.000    0.000    0.033    0.001 inspect.py:1688(getframeinfo)
   384096    0.030    0.000    0.030    0.000 {method 'isdigit' of 'str' objects}
     3218    0.002    0.000    0.030    0.000 db_path.py:106(parent)
     7355    0.004    0.000    0.029    0.000 pathlib.py:711(joinpath)
       38    0.013    0.000    0.029    0.001 inspect.py:988(getmodule)
      462    0.001    0.000    0.029    0.000 pathlib.py:164(select_from)
2763/2757    0.027    0.000    0.029    0.000 {method 'flatten' of 'numpy.ndarray' objects}
   454364    0.028    0.000    0.028    0.000 pathlib.py:560(root)
     3218    0.005    0.000    0.028    0.000 db_path.py:81(Parent)
      2/1    0.025    0.012    0.027    0.027 decorator.py:232(fun)
     2765    0.025    0.000    0.025    0.000 {built-in method numpy.array}
       29    0.000    0.000    0.025    0.001 inspect.py:1070(findsource)
        1    0.000    0.000    0.024    0.024 update_jobs.py:214(clear)
        1    0.024    0.024    0.024    0.024 {method 'clear' of 'list' objects}
      918    0.002    0.000    0.020    0.000 cal.py:187(td)
     4153    0.012    0.000    0.019    0.000 <frozen posixpath>:71(join)
     3674    0.007    0.000    0.019    0.000 common.py:1606(pandas_dtype)
     2184    0.010    0.000    0.016    0.000 ipkernel.py:781(_clean_thread_parent_frames)
      934    0.014    0.000    0.014    0.000 {method 'astype' of 'numpy.ndarray' objects}
       64    0.000    0.000    0.014    0.000 inspect.py:951(getsourcefile)
      918    0.001    0.000    0.014    0.000 trade_date.py:76(offset)
22629/22166    0.004    0.000    0.013    0.000 {built-in method builtins.getattr}
      459    0.000    0.000    0.013    0.000 parallel.py:173(submit)
      918    0.008    0.000    0.013    0.000 trade_date.py:80(_cls_offset)
      918    0.004    0.000    0.013    0.000 arraysetops.py:524(in1d)
      918    0.001    0.000    0.013    0.000 df_handler.py:116(new_mapper)
      459    0.001    0.000    0.012    0.000 thread.py:165(submit)
     1832    0.005    0.000    0.012    0.000 managers.py:1863(from_array)
     1840    0.005    0.000    0.012    0.000 construction.py:517(sanitize_array)
     2772    0.003    0.000    0.011    0.000 generic.py:6320(__setattr__)
    12280    0.004    0.000    0.011    0.000 update_jobs.py:46(__init__)
      918    0.000    0.000    0.011    0.000 db_path.py:214(path_exact)
      918    0.002    0.000    0.011    0.000 db_path.py:97(PathExact)
    26847    0.007    0.000    0.011    0.000 factor_calc.py:51(__get__)
      918    0.002    0.000    0.010    0.000 df_handler.py:52(load_process_pandas)
 28489/56    9.193    0.000    0.010    0.000 {built-in method posix.listdir}
      916    0.002    0.000    0.010    0.000 series.py:6470(any)
     2750    0.002    0.000    0.009    0.000 config.py:145(_get_option)
     3676    0.003    0.000    0.009    0.000 generic.py:2082(empty)
      459    0.005    0.000    0.009    0.000 _base.py:537(set_result)
      916    0.001    0.000    0.008    0.000 factor_calc.py:93(__get__)
      916    0.001    0.000    0.008    0.000 construction.py:96(arrays_to_mgr)
      459    0.000    0.000    0.007    0.000 _base.py:328(__init__)
     1832    0.001    0.000    0.007    0.000 generic.py:511(_validate_dtype)
      453    0.000    0.000    0.007    0.000 factor_calc.py:98(__get__)
      918    0.001    0.000    0.007    0.000 series.py:6429(_reduce)
     3684    0.006    0.000    0.007    0.000 generic.py:278(__init__)
     2346    0.007    0.000    0.007    0.000 {built-in method builtins.max}
        1    0.000    0.000    0.006    0.006 update_jobs.py:223(sort_jobs)
        1    0.004    0.004    0.006    0.006 {method 'sort' of 'list' objects}
     2756    0.002    0.000    0.006    0.000 generic.py:807(_set_axis)
      918    0.006    0.000    0.006    0.000 numeric.py:203(ones_like)
    44578    0.006    0.000    0.006    0.000 {built-in method builtins.hasattr}
     1845    0.001    0.000    0.006    0.000 typing.py:1221(__instancecheck__)
     2748    0.002    0.000    0.006    0.000 series.py:784(name)
    43205    0.004    0.000    0.005    0.000 inspect.py:298(ismodule)
    12281    0.003    0.000    0.005    0.000 module.py:281(vb_level)
      916    0.002    0.000    0.005    0.000 managers.py:2121(create_block_manager_from_column_arrays)
      920    0.001    0.000    0.005    0.000 df_handler.py:120(apply_mapper)
     9234    0.002    0.000    0.005    0.000 generic.py:42(_instancecheck)
     7364    0.002    0.000    0.005    0.000 generic.py:2140(<genexpr>)
     1840    0.001    0.000    0.005    0.000 warnings.py:168(simplefilter)
     2750    0.002    0.000    0.005    0.000 config.py:127(_get_single_key)
      920    0.001    0.000    0.005    0.000 missing.py:261(_isna_array)
      916    0.000    0.000    0.005    0.000 nanops.py:482(nanany)
      916    0.001    0.000    0.005    0.000 factor.py:340(STOCK)
     1840    0.002    0.000    0.004    0.000 api.py:386(default_index)
     2754    0.002    0.000    0.004    0.000 trade_date.py:26(__init__)
     2758    0.001    0.000    0.004    0.000 base.py:7716(maybe_extract_name)
     1845    0.001    0.000    0.004    0.000 typing.py:1492(__subclasscheck__)
      916    0.001    0.000    0.004    0.000 {method 'any' of 'numpy.ndarray' objects}
     4141    0.002    0.000    0.004    0.000 {built-in method builtins.all}
      934    0.003    0.000    0.004    0.000 generic.py:6255(__finalize__)
        1    0.000    0.000    0.004    0.004 updater.py:53(calculators)
      918    0.004    0.000    0.004    0.000 singleton.py:11(get_instance)
      460    0.001    0.000    0.004    0.000 factor_calc.py:581(iter)
    26847    0.004    0.000    0.004    0.000 factor_calc.py:41(__get__)
    42846    0.004    0.000    0.004    0.000 {method 'get' of 'dict' objects}
      459    0.000    0.000    0.004    0.000 thread.py:184(_adjust_thread_count)
     1844    0.003    0.000    0.004    0.000 blocks.py:2789(new_block)
     2748    0.001    0.000    0.004    0.000 common.py:1581(validate_all_hashable)
     1840    0.002    0.000    0.004    0.000 warnings.py:184(_add_filter)
      916    0.000    0.000    0.004    0.000 _methods.py:55(_any)
     2756    0.001    0.000    0.004    0.000 managers.py:236(set_axis)
      916    0.001    0.000    0.003    0.000 logger.py:346(only_once)
      459    0.001    0.000    0.003    0.000 parallel.py:121(unwrap)
      930    0.003    0.000    0.003    0.000 {method 'reduce' of 'numpy.ufunc' objects}
      916    0.003    0.000    0.003    0.000 missing.py:305(_isna_string_dtype)
    15614    0.002    0.000    0.003    0.000 range.py:999(__len__)
    27100    0.003    0.000    0.003    0.000 {built-in method _stat.S_ISDIR}
     3664    0.001    0.000    0.003    0.000 series.py:734(name)
     4136    0.002    0.000    0.003    0.000 pathlib.py:429(_format_parsed_parts)
      459    0.001    0.000    0.003    0.000 threading.py:468(acquire)
      920    0.000    0.000    0.003    0.000 df_handler.py:20(reset_index_pandas)
     6455    0.001    0.000    0.003    0.000 {built-in method builtins.issubclass}
     1842    0.002    0.000    0.003    0.000 blocks.py:2718(maybe_coerce_values)
     1092    0.002    0.000    0.003    0.000 threading.py:1535(enumerate)
     9234    0.002    0.000    0.003    0.000 generic.py:37(_check)
     2756    0.001    0.000    0.003    0.000 base.py:86(_validate_set_axis)
     2754    0.002    0.000    0.003    0.000 trade_date.py:21(__new__)
     4584    0.001    0.000    0.003    0.000 series.py:831(_values)
     1850    0.002    0.000    0.003    0.000 range.py:201(_simple_new)
      463    0.001    0.000    0.003    0.000 factor_calc.py:608(match_attrs)
      467    0.000    0.000    0.003    0.000 threading.py:424(notify_all)
     1371    0.000    0.000    0.003    0.000 factor_calc.py:109(__get__)
    17197    0.003    0.000    0.003    0.000 threading.py:1198(ident)
    13728    0.002    0.000    0.002    0.000 {method '__exit__' of 'posix.ScandirIterator' objects}
       27    0.000    0.000    0.002    0.000 linecache.py:52(checkcache)
      465    0.001    0.000    0.002    0.000 cal.py:40(get_cds)
     3695    0.002    0.000    0.002    0.000 {built-in method numpy.empty}
     2750    0.002    0.000    0.002    0.000 config.py:635(_get_root)
     3217    0.002    0.000    0.002    0.000 db_path.py:53(__new__)
    12280    0.002    0.000    0.002    0.000 update_jobs.py:224(<lambda>)
      916    0.002    0.000    0.002    0.000 once.py:45(run)
      916    0.001    0.000    0.002    0.000 base.py:840(__iter__)
     1836    0.001    0.000    0.002    0.000 basic.py:79(td_for_cd)
     9168    0.001    0.000    0.002    0.000 base.py:7621(ensure_index)
     3680    0.001    0.000    0.002    0.000 <frozen abc>:117(__instancecheck__)
     7346    0.001    0.000    0.002    0.000 inference.py:334(is_hashable)
      924    0.000    0.000    0.002    0.000 managers.py:1782(_consolidate_inplace)
     2748    0.002    0.000    0.002    0.000 generic.py:6303(__getattr__)
     4584    0.002    0.000    0.002    0.000 managers.py:2004(internal_values)
     3690    0.001    0.000    0.002    0.000 generic.py:586(_get_axis)
      475    0.001    0.000    0.002    0.000 threading.py:394(notify)
      468    0.001    0.000    0.002    0.000 threading.py:277(__init__)
      916    0.001    0.000    0.002    0.000 cast.py:1528(construct_1d_arraylike_from_scalar)
     2750    0.001    0.000    0.002    0.000 config.py:676(_translate_key)
      924    0.000    0.000    0.002    0.000 managers.py:1764(is_consolidated)
      2/1    0.000    0.000    0.002    0.002 history.py:92(only_when_enabled)
     1862    0.001    0.000    0.002    0.000 threading.py:299(__enter__)
     1845    0.001    0.000    0.002    0.000 <frozen abc>:121(__subclasscheck__)
     1840    0.002    0.000    0.002    0.000 {method 'remove' of 'list' objects}
     1842    0.001    0.000    0.002    0.000 warnings.py:484(__enter__)
     5496    0.001    0.000    0.002    0.000 common.py:1600(<genexpr>)
     1838    0.001    0.000    0.001    0.000 base.py:549(find)
     4169    0.001    0.000    0.001    0.000 <frozen posixpath>:41(_get_sep)
     6864    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}
     4142    0.001    0.000    0.001    0.000 {method 'join' of 'str' objects}
      6/1    0.001    0.000    0.001    0.001 factor_calc.py:809(stored_dates)
      463    0.000    0.000    0.001    0.000 factor_calc.py:81(__get__)
      916    0.001    0.000    0.001    0.000 managers.py:2190(_form_blocks)
     3680    0.001    0.000    0.001    0.000 {built-in method _abc._abc_instancecheck}
     2763    0.001    0.000    0.001    0.000 arraysetops.py:125(_unpack_tuple)
     1848    0.001    0.000    0.001    0.000 blocks.py:2747(get_block_type)
      916    0.000    0.000    0.001    0.000 common.py:301(maybe_iterable_to_list)
      916    0.000    0.000    0.001    0.000 series.py:914(__len__)
      924    0.001    0.000    0.001    0.000 managers.py:1772(_consolidate_check)
      463    0.000    0.000    0.001    0.000 factor_calc.py:88(is_market)
      459    0.001    0.000    0.001    0.000 _base.py:497(set_running_or_notify_cancel)
      918    0.000    0.000    0.001    0.000 db_path.py:121(syntax)
     1842    0.001    0.000    0.001    0.000 warnings.py:505(__exit__)
     1845    0.001    0.000    0.001    0.000 {built-in method _abc._abc_subclasscheck}
    12282    0.001    0.000    0.001    0.000 module.py:61(has)
        8    0.000    0.000    0.001    0.000 frame.py:6246(reset_index)
     1845    0.001    0.000    0.001    0.000 pathlib.py:52(_ignore_error)
        6    0.000    0.000    0.001    0.000 base_events.py:1922(_run_once)
     1836    0.001    0.000    0.001    0.000 typing.py:1612(__instancecheck__)
        7    0.000    0.000    0.001    0.000 events.py:86(_run)
    12282    0.001    0.000    0.001    0.000 module.py:46(get)
        7    0.000    0.000    0.001    0.000 {method 'run' of '_contextvars.Context' objects}
     3684    0.001    0.000    0.001    0.000 flags.py:51(__init__)
     1862    0.001    0.000    0.001    0.000 threading.py:302(__exit__)
      916    0.000    0.000    0.001    0.000 factor.py:231(cat0_to_meta)
      918    0.001    0.000    0.001    0.000 basic.py:99(trade_date_by_td_index)
      877    0.001    0.000    0.001    0.000 {built-in method _thread.allocate_lock}

In [2]:
from src.res.factor.calculator.updater import FactorStatsUpdater
from cProfile import Profile
updater = FactorStatsUpdater()
with Profile() as pr:
    updater.collect_jobs()
pr.print_stats('cumtime')

  --> FactorStatsUpdater >> Success : Collecting 12280 Jobs for FactorStatsUpdater
         26135435 function calls (26111936 primitive calls) in 9.515 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.012    0.012    9.489    9.489 updater.py:67(collect_jobs)
      459    0.060    0.000    9.357    0.020 factor_calc.py:563(stats_target_dates)
     1381    0.430    0.000    5.596    0.004 db_path.py:21(file_dates)
      462    0.001    0.000    4.858    0.011 db_path.py:295(dates)
      462    0.001    0.000    4.857    0.011 db_path.py:143(dates)
      462    0.034    0.000    4.852    0.011 db_path.py:31(dir_dates)
      453    0.001    0.000    4.614    0.010 factor_calc.py:448(stored_dates)
      919    0.000    0.000    4.004    0.004 cal.py:179(updated)
      919    0.001    0.000    4.004    0.004 db_path.py:320(max_date)
      919    0.008    0.000    4.002    0.004 db_path.py:168(max_date)
   146121    0.063    0.000    3.260    0.000 pathlib.py:1050(iterdir)
      919    0.041    0.000    3.200    0.003 db_path.py:138(years)
    30456    0.008    0.000    2.891    0.000 {built-in method builtins.any}
    28489    2.818    0.000    2.838    0.000 {built-in method posix.listdir}
  1178939    0.159    0.000    2.002    0.000 pathlib.py:583(name)
   320228    0.043    0.000    1.977    0.000 pathlib.py:1097(rglob)
   320215    0.052    0.000    1.925    0.000 pathlib.py:234(_select_from)
  1633303    0.241    0.000    1.869    0.000 pathlib.py:569(_tail)
   388232    0.150    0.000    1.666    0.000 pathlib.py:407(_load_parts)
   326630    0.358    0.000    1.461    0.000 pathlib.py:200(_select_from)
   388694    0.773    0.000    1.460    0.000 pathlib.py:387(_parse_path)
   450228    0.384    0.000    1.277    0.000 pathlib.py:1065(_make_child_relpath)
   842597    0.242    0.000    0.975    0.000 pathlib.py:1157(__init__)
   457583    0.184    0.000    0.805    0.000 pathlib.py:380(with_segments)
   842597    0.523    0.000    0.733    0.000 pathlib.py:358(__init__)
  3869014    0.417    0.000    0.417    0.000 {built-in method sys.intern}
     7313    0.005    0.000    0.412    0.000 pathlib.py:228(_iterate_directories)
     7313    0.243    0.000    0.389    0.000 pathlib.py:1112(walk)
   410747    0.148    0.000    0.299    0.000 pathlib.py:618(stem)
        6    0.000    0.000    0.254    0.042 factor_calc.py:809(stored_dates)
   842597    0.132    0.000    0.218    0.000 pathlib.py:1164(__new__)
      459    0.002    0.000    0.212    0.000 factor_calc.py:550(stats_stored_dates)
      918    0.003    0.000    0.207    0.000 df_io.py:364(load)
    13728    0.002    0.000    0.204    0.000 pathlib.py:1059(_scandir)
    13728    0.197    0.000    0.201    0.000 {built-in method posix.scandir}
   618724    0.126    0.000    0.183    0.000 trade_date.py:66(__ge__)
   388694    0.124    0.000    0.175    0.000 <frozen posixpath>:138(splitroot)
      918    0.001    0.000    0.166    0.000 df_io.py:212(load_df)
      918    0.002    0.000    0.159    0.000 df_io.py:35(load_pandas)
1879462/1873936    0.139    0.000    0.149    0.000 {built-in method builtins.isinstance}
      916    0.005    0.000    0.138    0.000 frame.py:694(__init__)
    29868    0.005    0.000    0.117    0.000 pathlib.py:835(stat)
      916    0.004    0.000    0.114    0.000 construction.py:423(dict_to_mgr)
    29899    0.067    0.000    0.112    0.000 {built-in method posix.stat}
   391451    0.093    0.000    0.093    0.000 {method 'split' of 'str' objects}
1587626/1571054    0.089    0.000    0.091    0.000 {built-in method builtins.len}
    27113    0.012    0.000    0.089    0.000 pathlib.py:870(is_dir)
   846413    0.087    0.000    0.087    0.000 {built-in method __new__ of type object at 0x1065d0a30}
   522316    0.037    0.000    0.080    0.000 pathlib.py:437(__str__)
2748/1832    0.012    0.000    0.078    0.000 series.py:389(__init__)
   790622    0.073    0.000    0.073    0.000 {method 'append' of 'list' objects}
   454364    0.032    0.000    0.070    0.000 pathlib.py:551(drive)
    72088    0.016    0.000    0.069    0.000 pathlib.py:447(__fspath__)
   620560    0.058    0.000    0.058    0.000 trade_date.py:42(__int__)
   410747    0.055    0.000    0.055    0.000 {method 'rfind' of 'str' objects}
   319803    0.055    0.000    0.055    0.000 {method 'match' of 're.Pattern' objects}
   402078    0.052    0.000    0.052    0.000 {method 'startswith' of 'str' objects}
   401906    0.052    0.000    0.052    0.000 {method 'endswith' of 'str' objects}
    12280    0.039    0.000    0.051    0.000 update_jobs.py:390(__init__)
   850480    0.049    0.000    0.049    0.000 {built-in method posix.fspath}
     2755    0.002    0.000    0.044    0.000 pathlib.py:852(exists)
      916    0.000    0.000    0.041    0.000 series.py:5784(isna)
      916    0.001    0.000    0.040    0.000 generic.py:8712(isna)
   392375    0.038    0.000    0.038    0.000 {method 'extend' of 'list' objects}
      920    0.000    0.000    0.036    0.000 missing.py:101(isna)
      920    0.003    0.000    0.036    0.000 missing.py:184(_isna)
   639532    0.034    0.000    0.034    0.000 pathlib.py:176(_select_from)
      916    0.002    0.000    0.033    0.000 series.py:607(_init_dict)
        1    0.000    0.000    0.031    0.031 module.py:145(success)
        1    0.000    0.000    0.031    0.031 logger.py:257(success)
        1    0.000    0.000    0.031    0.031 logger.py:65(new_stdout)
        1    0.000    0.000    0.031    0.031 logger.py:61(add_to_log_file)
        1    0.000    0.000    0.030    0.030 logger.py:51(find_calling_module)
        1    0.000    0.000    0.030    0.030 inspect.py:1779(stack)
        1    0.000    0.000    0.030    0.030 inspect.py:1749(getouterframes)
       29    0.000    0.000    0.030    0.001 inspect.py:1688(getframeinfo)
   384096    0.029    0.000    0.029    0.000 {method 'isdigit' of 'str' objects}
       38    0.013    0.000    0.028    0.001 inspect.py:988(getmodule)
      918    0.001    0.000    0.027    0.000 db_path.py:228(path)
   454364    0.027    0.000    0.027    0.000 pathlib.py:560(root)
        1    0.026    0.026    0.026    0.026 {method 'clear' of 'list' objects}
   319766    0.025    0.000    0.025    0.000 {method 'is_dir' of 'posix.DirEntry' objects}
     7355    0.003    0.000    0.025    0.000 pathlib.py:711(joinpath)
     3218    0.001    0.000    0.024    0.000 db_path.py:106(parent)
      918    0.003    0.000    0.023    0.000 arraysetops.py:939(setdiff1d)
     3218    0.004    0.000    0.023    0.000 db_path.py:81(Parent)
       29    0.000    0.000    0.022    0.001 inspect.py:1070(findsource)
     2763    0.002    0.000    0.022    0.000 arraysetops.py:138(unique)
     2765    0.022    0.000    0.022    0.000 {built-in method numpy.array}
     2763    0.009    0.000    0.019    0.000 arraysetops.py:323(_unique1d)
     4153    0.009    0.000    0.016    0.000 <frozen posixpath>:71(join)
     3674    0.006    0.000    0.015    0.000 common.py:1606(pandas_dtype)
     4144    0.015    0.000    0.015    0.000 {method 'sort' of 'numpy.ndarray' objects}
       64    0.000    0.000    0.014    0.000 inspect.py:951(getsourcefile)
      918    0.001    0.000    0.013    0.000 cal.py:187(td)
    12280    0.004    0.000    0.013    0.000 update_jobs.py:46(__init__)
     2772    0.003    0.000    0.011    0.000 generic.py:6320(__setattr__)
     1840    0.004    0.000    0.011    0.000 construction.py:517(sanitize_array)
    26847    0.007    0.000    0.010    0.000 factor_calc.py:51(__get__)
     1832    0.004    0.000    0.010    0.000 managers.py:1863(from_array)
      918    0.000    0.000    0.010    0.000 db_path.py:214(path_exact)
      918    0.001    0.000    0.009    0.000 db_path.py:97(PathExact)
      918    0.000    0.000    0.009    0.000 trade_date.py:76(offset)
      918    0.002    0.000    0.009    0.000 df_handler.py:52(load_process_pandas)
      918    0.005    0.000    0.009    0.000 trade_date.py:80(_cls_offset)
      462    0.000    0.000    0.009    0.000 pathlib.py:164(select_from)
22629/22166    0.003    0.000    0.008    0.000 {built-in method builtins.getattr}
     3676    0.002    0.000    0.008    0.000 generic.py:2082(empty)
     1914    0.004    0.000    0.008    0.000 ipkernel.py:781(_clean_thread_parent_frames)
     2750    0.002    0.000    0.007    0.000 config.py:145(_get_option)
      916    0.001    0.000    0.007    0.000 series.py:6470(any)
     1832    0.001    0.000    0.007    0.000 generic.py:511(_validate_dtype)
      916    0.001    0.000    0.007    0.000 construction.py:96(arrays_to_mgr)
      918    0.002    0.000    0.007    0.000 arraysetops.py:524(in1d)
    12281    0.004    0.000    0.006    0.000 module.py:281(vb_level)
        1    0.000    0.000    0.006    0.006 update_jobs.py:223(sort_jobs)
        1    0.004    0.004    0.006    0.006 {method 'sort' of 'list' objects}
     2756    0.002    0.000    0.006    0.000 generic.py:807(_set_axis)
      465    0.001    0.000    0.006    0.000 factor_calc.py:27(_slice_dates)
        1    0.000    0.000    0.006    0.006 updater.py:53(calculators)
    43174    0.006    0.000    0.006    0.000 {built-in method builtins.hasattr}
        2    0.000    0.000    0.006    0.003 feather_format.py:68(read_feather)
      460    0.001    0.000    0.006    0.000 factor_calc.py:581(iter)
      918    0.001    0.000    0.005    0.000 series.py:6429(_reduce)
    43205    0.004    0.000    0.005    0.000 inspect.py:298(ismodule)
     3684    0.005    0.000    0.005    0.000 generic.py:278(__init__)
     2748    0.002    0.000    0.005    0.000 series.py:784(name)
        2    0.000    0.000    0.005    0.003 feather.py:198(read_feather)
      465    0.003    0.000    0.005    0.000 cal.py:428(slice)
     7364    0.002    0.000    0.005    0.000 generic.py:2140(<genexpr>)
     9234    0.002    0.000    0.005    0.000 generic.py:42(_instancecheck)
      916    0.002    0.000    0.004    0.000 managers.py:2121(create_block_manager_from_column_arrays)
      463    0.001    0.000    0.004    0.000 factor_calc.py:608(match_attrs)
     1840    0.001    0.000    0.004    0.000 warnings.py:168(simplefilter)
      918    0.001    0.000    0.004    0.000 df_handler.py:116(new_mapper)
     2750    0.002    0.000    0.004    0.000 config.py:127(_get_single_key)
    42846    0.004    0.000    0.004    0.000 {method 'get' of 'dict' objects}
     2343    0.004    0.000    0.004    0.000 {built-in method builtins.max}
        2    0.004    0.002    0.004    0.002 feather.py:230(read_table)
     2758    0.001    0.000    0.004    0.000 base.py:7716(maybe_extract_name)
      934    0.003    0.000    0.004    0.000 generic.py:6255(__finalize__)
    26847    0.004    0.000    0.004    0.000 factor_calc.py:41(__get__)
    12280    0.002    0.000    0.004    0.000 update_jobs.py:217(append)
     4141    0.002    0.000    0.004    0.000 {built-in method builtins.all}
     2748    0.001    0.000    0.004    0.000 common.py:1581(validate_all_hashable)
     2756    0.001    0.000    0.004    0.000 managers.py:236(set_axis)
      920    0.000    0.000    0.004    0.000 df_handler.py:120(apply_mapper)
      920    0.001    0.000    0.003    0.000 missing.py:261(_isna_array)
      916    0.001    0.000    0.003    0.000 factor_calc.py:93(__get__)
     1386    0.001    0.000    0.003    0.000 typing.py:1221(__instancecheck__)
      916    0.000    0.000    0.003    0.000 nanops.py:482(nanany)
    15614    0.002    0.000    0.003    0.000 range.py:999(__len__)
     1840    0.001    0.000    0.003    0.000 api.py:386(default_index)
     1840    0.001    0.000    0.003    0.000 warnings.py:184(_add_filter)
     1844    0.002    0.000    0.003    0.000 blocks.py:2789(new_block)
     3664    0.001    0.000    0.003    0.000 series.py:734(name)
     2754    0.001    0.000    0.003    0.000 trade_date.py:26(__init__)
     4584    0.001    0.000    0.003    0.000 series.py:831(_values)
      916    0.001    0.000    0.003    0.000 logger.py:346(only_once)
      916    0.001    0.000    0.003    0.000 {method 'any' of 'numpy.ndarray' objects}
     2756    0.001    0.000    0.003    0.000 base.py:86(_validate_set_axis)
     1386    0.001    0.000    0.003    0.000 typing.py:1492(__subclasscheck__)
     9234    0.002    0.000    0.003    0.000 generic.py:37(_check)
     4136    0.001    0.000    0.003    0.000 pathlib.py:429(_format_parsed_parts)
      918    0.002    0.000    0.002    0.000 numeric.py:203(ones_like)
      920    0.000    0.000    0.002    0.000 df_handler.py:20(reset_index_pandas)
     1842    0.001    0.000    0.002    0.000 blocks.py:2718(maybe_coerce_values)
      916    0.000    0.000    0.002    0.000 _methods.py:55(_any)
      453    0.000    0.000    0.002    0.000 factor_calc.py:98(__get__)
     1850    0.001    0.000    0.002    0.000 range.py:201(_simple_new)
    12280    0.001    0.000    0.002    0.000 update_jobs.py:224(<lambda>)
      916    0.002    0.000    0.002    0.000 missing.py:305(_isna_string_dtype)
    27100    0.002    0.000    0.002    0.000 {built-in method _stat.S_ISDIR}
      463    0.000    0.000    0.002    0.000 factor_calc.py:81(__get__)
     5996    0.001    0.000    0.002    0.000 {built-in method builtins.issubclass}
      930    0.002    0.000    0.002    0.000 {method 'reduce' of 'numpy.ufunc' objects}
      916    0.001    0.000    0.002    0.000 base.py:840(__iter__)
     9168    0.001    0.000    0.002    0.000 base.py:7621(ensure_index)
     4584    0.002    0.000    0.002    0.000 managers.py:2004(internal_values)
     2748    0.002    0.000    0.002    0.000 generic.py:6303(__getattr__)
     2750    0.001    0.000    0.002    0.000 config.py:635(_get_root)
      957    0.001    0.000    0.002    0.000 threading.py:1535(enumerate)
      2/1    0.000    0.000    0.002    0.002 decorator.py:232(fun)
     7346    0.001    0.000    0.002    0.000 inference.py:334(is_hashable)
      916    0.002    0.000    0.002    0.000 once.py:45(run)
     1371    0.000    0.000    0.002    0.000 factor_calc.py:109(__get__)
      463    0.000    0.000    0.002    0.000 factor_calc.py:88(is_market)
      924    0.000    0.000    0.002    0.000 managers.py:1782(_consolidate_inplace)
     3690    0.001    0.000    0.002    0.000 generic.py:586(_get_axis)
     3217    0.002    0.000    0.002    0.000 db_path.py:53(__new__)
     2754    0.001    0.000    0.002    0.000 trade_date.py:21(__new__)
     2763    0.002    0.000    0.002    0.000 {method 'flatten' of 'numpy.ndarray' objects}
     3680    0.001    0.000    0.002    0.000 <frozen abc>:117(__instancecheck__)
     5496    0.001    0.000    0.001    0.000 common.py:1600(<genexpr>)
      924    0.000    0.000    0.001    0.000 managers.py:1764(is_consolidated)
    13728    0.001    0.000    0.001    0.000 {method '__exit__' of 'posix.ScandirIterator' objects}
      2/1    0.000    0.000    0.001    0.001 history.py:92(only_when_enabled)
     3695    0.001    0.000    0.001    0.000 {built-in method numpy.empty}
     2750    0.001    0.000    0.001    0.000 config.py:676(_translate_key)
    12282    0.001    0.000    0.001    0.000 module.py:61(has)
     1838    0.001    0.000    0.001    0.000 base.py:549(find)
      916    0.001    0.000    0.001    0.000 cast.py:1528(construct_1d_arraylike_from_scalar)
     1836    0.001    0.000    0.001    0.000 basic.py:79(td_for_cd)
     1840    0.001    0.000    0.001    0.000 {method 'remove' of 'list' objects}
     1842    0.001    0.000    0.001    0.000 warnings.py:484(__enter__)
    12282    0.001    0.000    0.001    0.000 module.py:46(get)
     1848    0.001    0.000    0.001    0.000 blocks.py:2747(get_block_type)
      916    0.000    0.000    0.001    0.000 factor.py:340(STOCK)
        2    0.000    0.000    0.001    0.001 pandas_compat.py:780(table_to_dataframe)
      916    0.000    0.000    0.001    0.000 series.py:914(__len__)
     4169    0.001    0.000    0.001    0.000 <frozen posixpath>:41(_get_sep)
     4142    0.001    0.000    0.001    0.000 {method 'join' of 'str' objects}
      465    0.000    0.000    0.001    0.000 cal.py:40(get_cds)
      924    0.001    0.000    0.001    0.000 managers.py:1772(_consolidate_check)
      916    0.000    0.000    0.001    0.000 common.py:301(maybe_iterable_to_list)
     7656    0.001    0.000    0.001    0.000 threading.py:1198(ident)
        1    0.000    0.000    0.001    0.001 logfile.py:212(write)
      918    0.000    0.000    0.001    0.000 db_path.py:121(syntax)
     6864    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}
        1    0.000    0.000    0.001    0.001 logfile.py:184(write_entry)
      916    0.001    0.000    0.001    0.000 managers.py:2190(_form_blocks)
     1842    0.001    0.000    0.001    0.000 warnings.py:505(__exit__)
        1    0.001    0.001    0.001    0.001 {method '__exit__' of '_io._IOBase' objects}
     3680    0.001    0.000    0.001    0.000 {built-in method _abc._abc_instancecheck}
     3684    0.001    0.000    0.001    0.000 flags.py:51(__init__)
     2763    0.001    0.000    0.001    0.000 arraysetops.py:125(_unpack_tuple)
      924    0.000    0.000    0.001    0.000 construction.py:693(_sanitize_ndim)
    12280    0.001    0.000    0.001    0.000 update_jobs.py:403(sort_key)
      918    0.000    0.000    0.001    0.000 base.py:74(__len__)
      918    0.001    0.000    0.001    0.000 singleton.py:11(get_instance)
     1856    0.001    0.000    0.001    0.000 construction.py:481(ensure_wrapped_if_datetimelike)
      916    0.000    0.000    0.001    0.000 factor.py:231(cat0_to_meta)
      916    0.000    0.000    0.001    0.000 common.py:568(require_length_match)
     1386    0.000    0.000    0.001    0.000 <frozen abc>:121(__subclasscheck__)
      934    0.001    0.000    0.001    0.000 {method 'astype' of 'numpy.ndarray' objects}
     1845    0.000    0.000    0.001    0.000 pathlib.py:52(_ignore_error)
     1836    0.001    0.000    0.001    0.000 typing.py:1612(__instancecheck__)
     1840    0.001    0.000    0.001    0.000 construction.py:416(extract_array)
     7361    0.001    0.000    0.001    0.000 {built-in method builtins.hash}
      918    0.000    0.000    0.001    0.000 basic.py:99(trade_date_by_td_index)
     3217    0.001    0.000    0.001    0.000 db_path.py:58(__init__)
      918    0.000    0.000    0.001    0.000 db_path.py:111(by_name)
        5    0.000    0.000    0.001    0.000 events.py:86(_run)
     5526    0.001    0.000    0.001    0.000 {built-in method numpy.asanyarray}
        5    0.000    0.000    0.001    0.000 {method 'run' of '_contextvars.Context' objects}
      918    0.000    0.000    0.001    0.000 trade_date.py:57(__lt__)
      916    0.000    0.000    0.001    0.000 missing.py:673(na_value_for_dtype)
     4610    0.001    0.000    0.001    0.000 generic.py:572(_get_axis_number)
       29    0.000    0.000    0.001    0.000 inspect.py:1681(_get_code_position)
        2    0.000    0.000    0.001    0.000 pandas_compat.py:939(_deserialize_column_index)
       37    0.000    0.000    0.000    0.000 {built-in method builtins.next}
        1    0.000    0.000    0.000    0.000 history.py:1024(writeout_cache)
     2750    0.000    0.000    0.000    0.000 config.py:617(_select_options)
     3830    0.000    0.000    0.000    0.000 {method 'keys' of 'dict' objects}
        3    0.000    0.000    0.000    0.000 zmqstream.py:573(_handle_events)
     2754    0.000    0.000    0.000    0.000 basic.py:67(pos_cd)
        2    0.000    0.000    0.000    0.000 frame.py:11627(all)
        2    0.000    0.000    0.000    0.000 asyncio.py:206(_handle_events)
     2754    0.000    0.000    0.000    0.000 arraysetops.py:630(<genexpr>)
        8    0.000    0.000    0.000    0.000 frame.py:6246(reset_index)
        2    0.000    0.000    0.000    0.000 generic.py:12188(_logical_func)

In [3]:
pr.print_stats('tottime')

         26135435 function calls (26111936 primitive calls) in 9.515 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    28489    2.818    0.000    2.838    0.000 {built-in method posix.listdir}
   388694    0.773    0.000    1.460    0.000 pathlib.py:387(_parse_path)
   842597    0.523    0.000    0.733    0.000 pathlib.py:358(__init__)
     1381    0.430    0.000    5.596    0.004 db_path.py:21(file_dates)
  3869014    0.417    0.000    0.417    0.000 {built-in method sys.intern}
   450228    0.384    0.000    1.277    0.000 pathlib.py:1065(_make_child_relpath)
   326630    0.358    0.000    1.461    0.000 pathlib.py:200(_select_from)
     7313    0.243    0.000    0.389    0.000 pathlib.py:1112(walk)
   842597    0.242    0.000    0.975    0.000 pathlib.py:1157(__init__)
  1633303    0.241    0.000    1.869    0.000 pathlib.py:569(_tail)
    13728    0.197    0.000    0.201    0.000 {built-in method posix.scandir}
   457583    0.184    0.000    0.805    0.000 pathlib.py:380(with_segments)
  1178939    0.159    0.000    2.002    0.000 pathlib.py:583(name)
   388232    0.150    0.000    1.666    0.000 pathlib.py:407(_load_parts)
   410747    0.148    0.000    0.299    0.000 pathlib.py:618(stem)
1879462/1873936    0.139    0.000    0.149    0.000 {built-in method builtins.isinstance}
   842597    0.132    0.000    0.218    0.000 pathlib.py:1164(__new__)
   618724    0.126    0.000    0.183    0.000 trade_date.py:66(__ge__)
   388694    0.124    0.000    0.175    0.000 <frozen posixpath>:138(splitroot)
   391451    0.093    0.000    0.093    0.000 {method 'split' of 'str' objects}
1587626/1571054    0.089    0.000    0.091    0.000 {built-in method builtins.len}
   846413    0.087    0.000    0.087    0.000 {built-in method __new__ of type object at 0x1065d0a30}
   790622    0.073    0.000    0.073    0.000 {method 'append' of 'list' objects}
    29899    0.067    0.000    0.112    0.000 {built-in method posix.stat}
   146121    0.063    0.000    3.260    0.000 pathlib.py:1050(iterdir)
      459    0.060    0.000    9.357    0.020 factor_calc.py:563(stats_target_dates)
   620560    0.058    0.000    0.058    0.000 trade_date.py:42(__int__)
   410747    0.055    0.000    0.055    0.000 {method 'rfind' of 'str' objects}
   319803    0.055    0.000    0.055    0.000 {method 'match' of 're.Pattern' objects}
   402078    0.052    0.000    0.052    0.000 {method 'startswith' of 'str' objects}
   401906    0.052    0.000    0.052    0.000 {method 'endswith' of 'str' objects}
   320215    0.052    0.000    1.925    0.000 pathlib.py:234(_select_from)
   850480    0.049    0.000    0.049    0.000 {built-in method posix.fspath}
   320228    0.043    0.000    1.977    0.000 pathlib.py:1097(rglob)
      919    0.041    0.000    3.200    0.003 db_path.py:138(years)
    12280    0.039    0.000    0.051    0.000 update_jobs.py:390(__init__)
   392375    0.038    0.000    0.038    0.000 {method 'extend' of 'list' objects}
   522316    0.037    0.000    0.080    0.000 pathlib.py:437(__str__)
   639532    0.034    0.000    0.034    0.000 pathlib.py:176(_select_from)
      462    0.034    0.000    4.852    0.011 db_path.py:31(dir_dates)
   454364    0.032    0.000    0.070    0.000 pathlib.py:551(drive)
   384096    0.029    0.000    0.029    0.000 {method 'isdigit' of 'str' objects}
   454364    0.027    0.000    0.027    0.000 pathlib.py:560(root)
        1    0.026    0.026    0.026    0.026 {method 'clear' of 'list' objects}
   319766    0.025    0.000    0.025    0.000 {method 'is_dir' of 'posix.DirEntry' objects}
     2765    0.022    0.000    0.022    0.000 {built-in method numpy.array}
    72088    0.016    0.000    0.069    0.000 pathlib.py:447(__fspath__)
     4144    0.015    0.000    0.015    0.000 {method 'sort' of 'numpy.ndarray' objects}
       38    0.013    0.000    0.028    0.001 inspect.py:988(getmodule)
        1    0.012    0.012    9.489    9.489 updater.py:67(collect_jobs)
2748/1832    0.012    0.000    0.078    0.000 series.py:389(__init__)
    27113    0.012    0.000    0.089    0.000 pathlib.py:870(is_dir)
     2763    0.009    0.000    0.019    0.000 arraysetops.py:323(_unique1d)
     4153    0.009    0.000    0.016    0.000 <frozen posixpath>:71(join)
      919    0.008    0.000    4.002    0.004 db_path.py:168(max_date)
    30456    0.008    0.000    2.891    0.000 {built-in method builtins.any}
    26847    0.007    0.000    0.010    0.000 factor_calc.py:51(__get__)
     3674    0.006    0.000    0.015    0.000 common.py:1606(pandas_dtype)
    43174    0.006    0.000    0.006    0.000 {built-in method builtins.hasattr}
      916    0.005    0.000    0.138    0.000 frame.py:694(__init__)
     7313    0.005    0.000    0.412    0.000 pathlib.py:228(_iterate_directories)
    29868    0.005    0.000    0.117    0.000 pathlib.py:835(stat)
      918    0.005    0.000    0.009    0.000 trade_date.py:80(_cls_offset)
     3684    0.005    0.000    0.005    0.000 generic.py:278(__init__)
      916    0.004    0.000    0.114    0.000 construction.py:423(dict_to_mgr)
     1914    0.004    0.000    0.008    0.000 ipkernel.py:781(_clean_thread_parent_frames)
     1840    0.004    0.000    0.011    0.000 construction.py:517(sanitize_array)
    12281    0.004    0.000    0.006    0.000 module.py:281(vb_level)
    42846    0.004    0.000    0.004    0.000 {method 'get' of 'dict' objects}
        1    0.004    0.004    0.006    0.006 {method 'sort' of 'list' objects}
     2343    0.004    0.000    0.004    0.000 {built-in method builtins.max}
        2    0.004    0.002    0.004    0.002 feather.py:230(read_table)
    12280    0.004    0.000    0.013    0.000 update_jobs.py:46(__init__)
    26847    0.004    0.000    0.004    0.000 factor_calc.py:41(__get__)
    43205    0.004    0.000    0.005    0.000 inspect.py:298(ismodule)
     1832    0.004    0.000    0.010    0.000 managers.py:1863(from_array)
     3218    0.004    0.000    0.023    0.000 db_path.py:81(Parent)
      465    0.003    0.000    0.005    0.000 cal.py:428(slice)
     7355    0.003    0.000    0.025    0.000 pathlib.py:711(joinpath)
22629/22166    0.003    0.000    0.008    0.000 {built-in method builtins.getattr}
      918    0.003    0.000    0.023    0.000 arraysetops.py:939(setdiff1d)
      918    0.003    0.000    0.207    0.000 df_io.py:364(load)
      934    0.003    0.000    0.004    0.000 generic.py:6255(__finalize__)
     2772    0.003    0.000    0.011    0.000 generic.py:6320(__setattr__)
      920    0.003    0.000    0.036    0.000 missing.py:184(_isna)
    12280    0.002    0.000    0.004    0.000 update_jobs.py:217(append)
     3676    0.002    0.000    0.008    0.000 generic.py:2082(empty)
    13728    0.002    0.000    0.204    0.000 pathlib.py:1059(_scandir)
      918    0.002    0.000    0.002    0.000 numeric.py:203(ones_like)
     2763    0.002    0.000    0.022    0.000 arraysetops.py:138(unique)
      918    0.002    0.000    0.007    0.000 arraysetops.py:524(in1d)
      916    0.002    0.000    0.002    0.000 missing.py:305(_isna_string_dtype)
    15614    0.002    0.000    0.003    0.000 range.py:999(__len__)
    27100    0.002    0.000    0.002    0.000 {built-in method _stat.S_ISDIR}
     9234    0.002    0.000    0.005    0.000 generic.py:42(_instancecheck)
      930    0.002    0.000    0.002    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     1844    0.002    0.000    0.003    0.000 blocks.py:2789(new_block)
      459    0.002    0.000    0.212    0.000 factor_calc.py:550(stats_stored_dates)
     2748    0.002    0.000    0.002    0.000 generic.py:6303(__getattr__)
     2750    0.002    0.000    0.004    0.000 config.py:127(_get_single_key)
     4584    0.002    0.000    0.002    0.000 managers.py:2004(internal_values)
     9234    0.002    0.000    0.003    0.000 generic.py:37(_check)
     2755    0.002    0.000    0.044    0.000 pathlib.py:852(exists)
     4141    0.002    0.000    0.004    0.000 {built-in method builtins.all}
      918    0.002    0.000    0.159    0.000 df_io.py:35(load_pandas)
     7364    0.002    0.000    0.005    0.000 generic.py:2140(<genexpr>)
     3217    0.002    0.000    0.002    0.000 db_path.py:53(__new__)
     2748    0.002    0.000    0.005    0.000 series.py:784(name)
     2756    0.002    0.000    0.006    0.000 generic.py:807(_set_axis)
     2750    0.002    0.000    0.007    0.000 config.py:145(_get_option)
      916    0.002    0.000    0.033    0.000 series.py:607(_init_dict)
      916    0.002    0.000    0.002    0.000 once.py:45(run)
      918    0.002    0.000    0.009    0.000 df_handler.py:52(load_process_pandas)
     2763    0.002    0.000    0.002    0.000 {method 'flatten' of 'numpy.ndarray' objects}
      916    0.002    0.000    0.004    0.000 managers.py:2121(create_block_manager_from_column_arrays)
     1840    0.001    0.000    0.003    0.000 warnings.py:184(_add_filter)
      957    0.001    0.000    0.002    0.000 threading.py:1535(enumerate)
    13728    0.001    0.000    0.001    0.000 {method '__exit__' of 'posix.ScandirIterator' objects}
     2754    0.001    0.000    0.003    0.000 trade_date.py:26(__init__)
     4136    0.001    0.000    0.003    0.000 pathlib.py:429(_format_parsed_parts)
      919    0.001    0.000    4.004    0.004 db_path.py:320(max_date)
     5996    0.001    0.000    0.002    0.000 {built-in method builtins.issubclass}
     3690    0.001    0.000    0.002    0.000 generic.py:586(_get_axis)
      918    0.001    0.000    0.166    0.000 df_io.py:212(load_df)
     9168    0.001    0.000    0.002    0.000 base.py:7621(ensure_index)
     3695    0.001    0.000    0.001    0.000 {built-in method numpy.empty}
     2750    0.001    0.000    0.002    0.000 config.py:635(_get_root)
    12280    0.001    0.000    0.002    0.000 update_jobs.py:224(<lambda>)
     1850    0.001    0.000    0.002    0.000 range.py:201(_simple_new)
    12282    0.001    0.000    0.001    0.000 module.py:61(has)
      916    0.001    0.000    0.007    0.000 construction.py:96(arrays_to_mgr)
      916    0.001    0.000    0.007    0.000 series.py:6470(any)
     7346    0.001    0.000    0.002    0.000 inference.py:334(is_hashable)
      918    0.001    0.000    0.009    0.000 db_path.py:97(PathExact)
     1842    0.001    0.000    0.002    0.000 blocks.py:2718(maybe_coerce_values)
     3218    0.001    0.000    0.024    0.000 db_path.py:106(parent)
     1840    0.001    0.000    0.001    0.000 {method 'remove' of 'list' objects}
      918    0.001    0.000    0.005    0.000 series.py:6429(_reduce)
    12282    0.001    0.000    0.001    0.000 module.py:46(get)
      463    0.001    0.000    0.004    0.000 factor_calc.py:608(match_attrs)
     4142    0.001    0.000    0.001    0.000 {method 'join' of 'str' objects}
     2754    0.001    0.000    0.002    0.000 trade_date.py:21(__new__)
      916    0.001    0.000    0.002    0.000 base.py:840(__iter__)
      918    0.001    0.000    0.013    0.000 cal.py:187(td)
     2748    0.001    0.000    0.004    0.000 common.py:1581(validate_all_hashable)
     3664    0.001    0.000    0.003    0.000 series.py:734(name)
     7656    0.001    0.000    0.001    0.000 threading.py:1198(ident)
     1842    0.001    0.000    0.001    0.000 warnings.py:484(__enter__)
     1840    0.001    0.000    0.004    0.000 warnings.py:168(simplefilter)
     2758    0.001    0.000    0.004    0.000 base.py:7716(maybe_extract_name)
      453    0.001    0.000    4.614    0.010 factor_calc.py:448(stored_dates)
     6864    0.001    0.000    0.001    0.000 {method 'pop' of 'list' objects}
      916    0.001    0.000    0.001    0.000 managers.py:2190(_form_blocks)
     1840    0.001    0.000    0.003    0.000 api.py:386(default_index)
      920    0.001    0.000    0.003    0.000 missing.py:261(_isna_array)
      916    0.001    0.000    0.003    0.000 factor_calc.py:93(__get__)
     2750    0.001    0.000    0.001    0.000 config.py:676(_translate_key)
      460    0.001    0.000    0.006    0.000 factor_calc.py:581(iter)
     4584    0.001    0.000    0.003    0.000 series.py:831(_values)
     1836    0.001    0.000    0.001    0.000 basic.py:79(td_for_cd)
      924    0.001    0.000    0.001    0.000 managers.py:1772(_consolidate_check)
        1    0.001    0.001    0.001    0.001 {method '__exit__' of '_io._IOBase' objects}
     3680    0.001    0.000    0.001    0.000 {built-in method _abc._abc_instancecheck}
     3684    0.001    0.000    0.001    0.000 flags.py:51(__init__)
      916    0.001    0.000    0.003    0.000 logger.py:346(only_once)
     5496    0.001    0.000    0.001    0.000 common.py:1600(<genexpr>)
     1838    0.001    0.000    0.001    0.000 base.py:549(find)
     1842    0.001    0.000    0.001    0.000 warnings.py:505(__exit__)
     2756    0.001    0.000    0.003    0.000 base.py:86(_validate_set_axis)
      916    0.001    0.000    0.001    0.000 cast.py:1528(construct_1d_arraylike_from_scalar)
    12280    0.001    0.000    0.001    0.000 update_jobs.py:403(sort_key)
     4169    0.001    0.000    0.001    0.000 <frozen posixpath>:41(_get_sep)
     1386    0.001    0.000    0.003    0.000 typing.py:1221(__instancecheck__)
     1848    0.001    0.000    0.001    0.000 blocks.py:2747(get_block_type)
     2756    0.001    0.000    0.004    0.000 managers.py:236(set_axis)
      462    0.001    0.000    4.858    0.011 db_path.py:295(dates)
     1386    0.001    0.000    0.003    0.000 typing.py:1492(__subclasscheck__)
      918    0.001    0.000    0.027    0.000 db_path.py:228(path)
     3680    0.001    0.000    0.002    0.000 <frozen abc>:117(__instancecheck__)
      934    0.001    0.000    0.001    0.000 {method 'astype' of 'numpy.ndarray' objects}
     1832    0.001    0.000    0.007    0.000 generic.py:511(_validate_dtype)
      916    0.001    0.000    0.040    0.000 generic.py:8712(isna)
      918    0.001    0.000    0.004    0.000 df_handler.py:116(new_mapper)
     7361    0.001    0.000    0.001    0.000 {built-in method builtins.hash}
     3217    0.001    0.000    0.001    0.000 db_path.py:58(__init__)
     1856    0.001    0.000    0.001    0.000 construction.py:481(ensure_wrapped_if_datetimelike)
      918    0.001    0.000    0.001    0.000 singleton.py:11(get_instance)
     5526    0.001    0.000    0.001    0.000 {built-in method numpy.asanyarray}
     2763    0.001    0.000    0.001    0.000 arraysetops.py:125(_unpack_tuple)
      916    0.001    0.000    0.003    0.000 {method 'any' of 'numpy.ndarray' objects}
     1836    0.001    0.000    0.001    0.000 typing.py:1612(__instancecheck__)
     1840    0.001    0.000    0.001    0.000 construction.py:416(extract_array)
     4610    0.001    0.000    0.001    0.000 generic.py:572(_get_axis_number)
      465    0.001    0.000    0.006    0.000 factor_calc.py:27(_slice_dates)
      462    0.001    0.000    4.857    0.011 db_path.py:143(dates)
       37    0.000    0.000    0.000    0.000 {built-in method builtins.next}
     2750    0.000    0.000    0.000    0.000 config.py:617(_select_options)
      918    0.000    0.000    0.001    0.000 basic.py:99(trade_date_by_td_index)
     3830    0.000    0.000    0.000    0.000 {method 'keys' of 'dict' objects}
      465    0.000    0.000    0.001    0.000 cal.py:40(get_cds)
      920    0.000    0.000    0.004    0.000 df_handler.py:120(apply_mapper)
     2754    0.000    0.000    0.000    0.000 basic.py:67(pos_cd)
      919    0.000    0.000    4.004    0.004 cal.py:179(updated)
      916    0.000    0.000    0.001    0.000 missing.py:673(na_value_for_dtype)
     2754    0.000    0.000    0.000    0.000 arraysetops.py:630(<genexpr>)
      916    0.000    0.000    0.001    0.000 factor.py:231(cat0_to_meta)
     1866    0.000    0.000    0.000    0.000 base.py:832(_reset_identity)
     5524    0.000    0.000    0.000    0.000 {built-in method _warnings._filters_mutated}
      918    0.000    0.000    0.010    0.000 db_path.py:214(path_exact)
      916    0.000    0.000    0.001    0.000 common.py:301(maybe_iterable_to_list)
      924    0.000    0.000    0.001    0.000 construction.py:693(_sanitize_ndim)
     1845    0.000    0.000    0.001    0.000 pathlib.py:52(_ignore_error)
        2    0.000    0.000    0.000    0.000 {method '__exit__' of 'sqlite3.Connection' objects}
     1836    0.000    0.000    0.000    0.000 {method 'ravel' of 'numpy.ndarray' objects}
      916    0.000    0.000    0.001    0.000 factor.py:340(STOCK)
      924    0.000    0.000    0.001    0.000 managers.py:1764(is_consolidated)
      916    0.000    0.000    0.003    0.000 nanops.py:482(nanany)
     1842    0.000    0.000    0.000    0.000 warnings.py:458(__init__)
     1386    0.000    0.000    0.000    0.000 {built-in method _abc._abc_subclasscheck}
     2752    0.000    0.000    0.000    0.000 config.py:649(_get_deprecated_option)
      918    0.000    0.000    0.001    0.000 trade_date.py:57(__lt__)
      934    0.000    0.000    0.000    0.000 flags.py:87(allows_duplicate_labels)
     2301    0.000    0.000    0.000    0.000 {method '__exit__' of '_thread.lock' objects}
      918    0.000    0.000    0.009    0.000 trade_date.py:76(offset)
      918    0.000    0.000    0.001    0.000 db_path.py:121(syntax)
      2/1    0.000    0.000    0.002    0.002 decorator.py:232(fun)
      459    0.000    0.000    0.000    0.000 singleton.py:32(__call__)
      918    0.000    0.000    0.000    0.000 basic.py:87(td_index_for_cd)
      918    0.000    0.000    0.001    0.000 db_path.py:111(by_name)
     1863    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
        8    0.000    0.000    0.000    0.000 {method 'copy' of 'dict' objects}
      918    0.000    0.000    0.001    0.000 base.py:74(__len__)
      924    0.000    0.000    0.002    0.000 managers.py:1782(_consolidate_inplace)
     1386    0.000    0.000    0.001    0.000 <frozen abc>:121(__subclasscheck__)
      916    0.000    0.000    0.002    0.000 _methods.py:55(_any)
      928    0.000    0.000    0.000    0.000 _validators.py:226(validate_bool_kwarg)
     1914    0.000    0.000    0.000    0.000 {method 'values' of 'dict' objects}
      920    0.000    0.000    0.002    0.000 df_handler.py:20(reset_index_pandas)
      918    0.000    0.000    0.000    0.000 trade_date.py:63(__gt__)
     1840    0.000    0.000    0.000    0.000 {method 'insert' of 'list' objects}
      918    0.000    0.000    0.000    0.000 db_path.py:71(ByName)
     1838    0.000    0.000    0.000    0.000 managers.py:1837(__init__)
     1371    0.000    0.000    0.002    0.000 factor_calc.py:109(__get__)
      920    0.000    0.000    0.036    0.000 missing.py:101(isna)
      934    0.000    0.000    0.000    0.000 __init__.py:34(using_copy_on_write)
      463    0.000    0.000    0.002    0.000 factor_calc.py:88(is_market)
      924    0.000    0.000    0.000    0.000 construction.py:732(_sanitize_str_dtypes)
      916    0.000    0.000    0.041    0.000 series.py:5784(isna)
      916    0.000    0.000    0.000    0.000 factor.py:205(category0)
      462    0.000    0.000    0.009    0.000 pathlib.py:164(select_from)
      916    0.000    0.000    0.001    0.000 common.py:568(require_length_match)
      918    0.000    0.000    0.000    0.000 df_handler.py:114(wrapped_mapper)
        2    0.000    0.000    0.001    0.001 pandas_compat.py:780(table_to_dataframe)
     2763    0.000    0.000    0.000    0.000 arraysetops.py:133(_unique_dispatcher)
      463    0.000    0.000    0.002    0.000 factor_calc.py:81(__get__)
      916    0.000    0.000    0.000    0.000 construction.py:196(mgr_to_mgr)
      924    0.000    0.000    0.000    0.000 construction.py:755(_maybe_repeat)
        2    0.000    0.000    0.005    0.003 feather.py:198(read_feather)
      916    0.000    0.000    0.000    0.000 construction.py:596(_homogenize)
     2748    0.000    0.000    0.000    0.000 series.py:1489(_clear_item_cache)

In [1]:
from src.res.model.model_module.application import ArchivedPredictorModel
model = ArchivedPredictorModel.from_model_str('gru@gru_avg@0')

In [2]:
block = model.hidden_block(20170101 , 20170105 , 20170103 , silent = False)

  --> Timer(Load DataBlock [y,day] at 20070101~20241211) finished! Cost 0.2592 Sec
  --> Timer(Align DataBlock [y,day]) finished! Cost 0.1631 Sec
early_test_dates: []
test_full_dates: [20170104 20170105 20170106 ... 20241209 20241210 20241211]
model_test_dates: [20170103 20170104 20170105]

In [3]:
from src.res.model.model_module.application import ArchivedPredictorModel
model = ArchivedPredictorModel.from_model_str('gru@gru_day@0')

In [4]:
block = model.hidden_block(20170101 , 20170105 , 20170103 , silent = False)

  --> Timer(Load DataBlock [y,day] at 20070101~20241211) finished! Cost 0.1535 Sec
  --> Timer(Align DataBlock [y,day]) finished! Cost 0.0972 Sec

In [5]:
block.date

array([20170103, 20170104, 20170105, 20170106, 20170109, 20170110,
       20170111, 20170112, 20170113, 20170116, 20170117, 20170118,
       20170119, 20170120, 20170123, 20170124, 20170125, 20170126,
       20170203, 20170206, 20170207, 20170208, 20170209, 20170210,
       20170213, 20170214, 20170215, 20170216, 20170217, 20170220,
       20170221, 20170222, 20170223, 20170224, 20170227, 20170228,
       20170301, 20170302, 20170303, 20170306, 20170307, 20170308,
       20170309, 20170310, 20170313, 20170314, 20170315, 20170316,
       20170317, 20170320, 20170321, 20170322, 20170323, 20170324,
       20170327, 20170328, 20170329, 20170330, 20170331, 20170405,
       20170406, 20170407, 20170410, 20170411, 20170412, 20170413,
       20170414, 20170417, 20170418, 20170419, 20170420, 20170421,
       20170424, 20170425, 20170426, 20170427, 20170428, 20170502,
       20170503, 20170504, 20170505, 20170508, 20170509, 20170510,
       20170511, 20170512, 20170515, 20170516, 20170517, 20170518,
       20170519, 20170522, 20170523, 20170524, 20170525, 20170526,
       20170531, 20170601, 20170602, 20170605, 20170606, 20170607,
       20170608, 20170609, 20170612, 20170613, 20170614, 20170615,
       20170616, 20170619, 20170620, 20170621, 20170622, 20170623,
       20170626, 20170627, 20170628, 20170629, 20170630, 20170703,
       20170704, 20170705, 20170706, 20170707, 20170710, 20170711,
       20170712, 20170713, 20170714, 20170717, 20170718, 20170719,
       20170720, 20170721, 20170724, 20170725, 20170726, 20170727,
       20170728, 20170731, 20170801, 20170802, 20170803, 20170804,
       20170807, 20170808, 20170809, 20170810, 20170811, 20170814,
       20170815, 20170816, 20170817, 20170818, 20170821, 20170822,
       20170823, 20170824, 20170825, 20170828, 20170829, 20170830,
       20170831, 20170901, 20170904, 20170905, 20170906, 20170907,
       20170908, 20170911, 20170912, 20170913, 20170914, 20170915,
       20170918, 20170919, 20170920, 20170921, 20170922, 20170925,
       20170926, 20170927, 20170928, 20170929, 20171009, 20171010,
       20171011, 20171012, 20171013, 20171016, 20171017, 20171018,
       20171019, 20171020, 20171023, 20171024, 20171025, 20171026,
       20171027, 20171030, 20171031, 20171101, 20171102, 20171103,
       20171106, 20171107, 20171108, 20171109, 20171110, 20171113,
       20171114, 20171115, 20171116, 20171117, 20171120, 20171121,
       20171122, 20171123, 20171124, 20171127, 20171128, 20171129,
       20171130, 20171201, 20171204, 20171205, 20171206, 20171207,
       20171208, 20171211, 20171212, 20171213, 20171214, 20171215,
       20171218, 20171219, 20171220, 20171221, 20171222, 20171225,
       20171226, 20171227, 20171228, 20171229])

In [ ]:
batch_data = model.batch_data(20170104 , 20170103)
batch_data.output.hidden

tensor([[-0.3915, -0.3443,  0.4069,  ...,  0.3598,  0.3319, -0.3887],
        [-0.0589, -0.1906,  0.0775,  ...,  0.0372,  0.0869, -0.1593],
        [ 0.0388, -0.1517, -0.0289,  ..., -0.0538, -0.0040, -0.0741],
        ...,
        [-0.2409, -0.2720,  0.2601,  ...,  0.1993,  0.2109, -0.2853],
        [ 0.0330, -0.1552, -0.0160,  ..., -0.0414,  0.0092, -0.0794],
        [ 0.0763, -0.1266, -0.1034,  ..., -0.1166, -0.0764, -0.0572]],
       device='mps:0')

In [ ]:
batch_data.hidden_df_pl(colname_prefix = model.model.model_full_name)

shape: (2_475, 34)
┌────────┬──────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ secid  ┆ date     ┆ gru_avg@0@ ┆ gru_avg@0@ ┆ … ┆ gru_avg@0@ ┆ gru_avg@0 ┆ gru_avg@0 ┆ gru_avg@0 │
│ ---    ┆ ---      ┆ 20170103@b ┆ 20170103@b ┆   ┆ 20170103@b ┆ @20170103 ┆ @20170103 ┆ @20170103 │
│ i64    ┆ i64      ┆ est.hidden ┆ est.hidden ┆   ┆ est.hidden ┆ @best.hid ┆ @best.hid ┆ @best.hid │
│        ┆          ┆ …          ┆ …          ┆   ┆ …          ┆ den…      ┆ den…      ┆ den…      │
│        ┆          ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│        ┆          ┆ f32        ┆ f32        ┆   ┆ f32        ┆ f32       ┆ f32       ┆ f32       │
╞════════╪══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1      ┆ 20170104 ┆ -0.391518  ┆ -0.344337  ┆ … ┆ -0.531863  ┆ 0.359802  ┆ 0.331948  ┆ -0.388693 │
│ 2      ┆ 20170104 ┆ -0.058927  ┆ -0.190594  ┆ … ┆ -0.210109  ┆ 0.037165  ┆ 0.086898  ┆ -0.159343 │
│ 4      ┆ 20170104 ┆ 0.038837   ┆ -0.151741  ┆ … ┆ -0.096914  ┆ -0.053778 ┆ -0.003955 ┆ -0.07411  │
│ 5      ┆ 20170104 ┆ -0.327795  ┆ -0.319639  ┆ … ┆ -0.460516  ┆ 0.310246  ┆ 0.262872  ┆ -0.339074 │
│ 6      ┆ 20170104 ┆ -0.358319  ┆ -0.339356  ┆ … ┆ -0.486123  ┆ 0.333871  ┆ 0.301682  ┆ -0.368806 │
│ …      ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 603993 ┆ 20170104 ┆ -0.61449   ┆ -0.473215  ┆ … ┆ -0.767785  ┆ 0.620125  ┆ 0.511186  ┆ -0.545246 │
│ 603996 ┆ 20170104 ┆ 0.102553   ┆ -0.117309  ┆ … ┆ -0.047386  ┆ -0.143748 ┆ -0.106214 ┆ -0.039728 │
│ 603997 ┆ 20170104 ┆ -0.240882  ┆ -0.27201   ┆ … ┆ -0.37392   ┆ 0.199293  ┆ 0.210866  ┆ -0.285268 │
│ 603998 ┆ 20170104 ┆ 0.033038   ┆ -0.155186  ┆ … ┆ -0.104923  ┆ -0.041392 ┆ 0.009166  ┆ -0.079417 │
│ 603999 ┆ 20170104 ┆ 0.076266   ┆ -0.1266    ┆ … ┆ -0.07401   ┆ -0.116563 ┆ -0.07642  ┆ -0.057189 │
└────────┴──────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
model.model.model_full_name

'gru_avg@0@20170103@best'

In [3]:
batch_data.hidden_df

AttributeError: 'BatchData' object has no attribute 'hidden_df'

In [3]:
model.dataloader.batch_dates

[20170103,
 20170104,
 20170105,
 20170106,
 20170109,
 20170110,
 20170111,
 20170112,
 20170113,
 20170116,
 20170117,
 20170118,
 20170119,
 20170120,
 20170123,
 20170124,
 20170125,
 20170126,
 20170203,
 20170206,
 20170207,
 20170208,
 20170209,
 20170210,
 20170213,
 20170214,
 20170215,
 20170216,
 20170217,
 20170220,
 20170221,
 20170222,
 20170223,
 20170224,
 20170227,
 20170228,
 20170301,
 20170302,
 20170303,
 20170306,
 20170307,
 20170308,
 20170309,
 20170310,
 20170313,
 20170314,
 20170315,
 20170316,
 20170317,
 20170320,
 20170321,
 20170322,
 20170323,
 20170324,
 20170327,
 20170328,
 20170329,
 20170330,
 20170331,
 20170405,
 20170406,
 20170407,
 20170410,
 20170411,
 20170412,
 20170413,
 20170414,
 20170417,
 20170418,
 20170419,
 20170420,
 20170421,
 20170424,
 20170425,
 20170426,
 20170427,
 20170428,
 20170502,
 20170503,
 20170504,
 20170505,
 20170508,
 20170509,
 20170510,
 20170511,
 20170512,
 20170515,
 20170516,
 20170517,
 20170518,
 20170519,
 20170522,
 20170523,
 20170524,
 20170525,
 20170526,
 20170531,
 20170601,
 20170602,
 20170605,
 20170606,
 20170607,
 20170608,
 20170609,
 20170612,
 20170613,
 20170614,
 20170615,
 20170616,
 20170619,
 20170620,
 20170621,
 20170622,
 20170623,
 20170626,
 20170627,
 20170628,
 20170629,
 20170630,
 20170703,
 20170704,
 20170705,
 20170706,
 20170707,
 20170710,
 20170711,
 20170712,
 20170713,
 20170714,
 20170717,
 20170718,
 20170719,
 20170720,
 20170721,
 20170724,
 20170725,
 20170726,
 20170727,
 20170728,
 20170731,
 20170801,
 20170802,
 20170803,
 20170804,
 20170807,
 20170808,
 20170809,
 20170810,
 20170811,
 20170814,
 20170815,
 20170816,
 20170817,
 20170818,
 20170821,
 20170822,
 20170823,
 20170824,
 20170825,
 20170828,
 20170829,
 20170830,
 20170831,
 20170901,
 20170904,
 20170905,
 20170906,
 20170907,
 20170908,
 20170911,
 20170912,
 20170913,
 20170914,
 20170915,
 20170918,
 20170919,
 20170920,
 20170921,
 20170922,
 20170925,
 20170926,
 20170927,
 20170928,
 20170929,
 20171009,
 20171010,
 20171011,
 20171012,
 20171013,
 20171016,
 20171017,
 20171018,
 20171019,
 20171020,
 20171023,
 20171024,
 20171025,
 20171026,
 20171027,
 20171030,
 20171031,
 20171101,
 20171102,
 20171103,
 20171106,
 20171107,
 20171108,
 20171109,
 20171110,
 20171113,
 20171114,
 20171115,
 20171116,
 20171117,
 20171120,
 20171121,
 20171122,
 20171123,
 20171124,
 20171127,
 20171128,
 20171129,
 20171130,
 20171201,
 20171204,
 20171205,
 20171206,
 20171207,
 20171208,
 20171211,
 20171212,
 20171213,
 20171214,
 20171215,
 20171218,
 20171219,
 20171220,
 20171221,
 20171222,
 20171225,
 20171226,
 20171227,
 20171228,
 20171229]

In [3]:
from src.res.factor.calculator import StockFactorHierarchy
calc = StockFactorHierarchy.get_factor('event_factor_momentum')()
calc.eval_factor_series(20241231)

Caution : Purging pooling weight of event_factor_momentum!

ValueError: factor weight is missing for ['atr_1m' 'ff_r2_1m']

In [1]:
from src.res.model.util import ModelPath
model_path = ModelPath('models/nn/gru@gru_global2top')

In [2]:
model_path2 = model_path.with_new_index(2)

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************